#Downloads and imports (~30s)

In [ ]:
%load_ext cuml.accel

In [ ]:
# download TA-Lib
!wget -q http://prdownloads.sourceforge.net/ta-lib/ta-lib-0.4.0-src.tar.gz
#!ls
!tar xvzf ta-lib-0.4.0-src.tar.gz
#!ls
import os
os.chdir('ta-lib') # Can't use !cd in co-lab
!./configure --prefix=/usr
!make
!make install
# wait ~ 30s
os.chdir('../')
#!ls
!pip install -q TA-Lib

ta-lib/
ta-lib/config.sub
ta-lib/aclocal.m4
ta-lib/CHANGELOG.TXT
ta-lib/include/
ta-lib/include/ta_abstract.h
ta-lib/include/ta_func.h
ta-lib/include/ta_common.h
ta-lib/include/ta_config.h.in
ta-lib/include/Makefile.am
ta-lib/include/ta_libc.h
ta-lib/include/ta_defs.h
ta-lib/missing
ta-lib/ta-lib.spec.in
ta-lib/config.guess
ta-lib/Makefile.in
ta-lib/ta-lib.dpkg.in
ta-lib/Makefile.am
ta-lib/autogen.sh
ta-lib/install-sh
ta-lib/configure
ta-lib/depcomp
ta-lib/HISTORY.TXT
ta-lib/configure.in
ta-lib/autom4te.cache/
ta-lib/autom4te.cache/output.0
ta-lib/autom4te.cache/requests
ta-lib/autom4te.cache/output.1
ta-lib/autom4te.cache/traces.0
ta-lib/autom4te.cache/traces.1
ta-lib/ltmain.sh
ta-lib/ta-lib-config.in
ta-lib/src/
ta-lib/src/ta_func/
ta-lib/src/ta_func/ta_MACDFIX.c
ta-lib/src/ta_func/ta_CDLPIERCING.c
ta-lib/src/ta_func/ta_DIV.c
ta-lib/src/ta_func/ta_ROCR100.c
ta-lib/src/ta_func/ta_ADXR.c
ta-lib/src/ta_func/ta_MAVP.c
ta-lib/src/ta_func/ta_CDLCLOSINGMARUBOZU.c
ta-lib/src/ta_func/ta_COSH.c
ta-lib/src/ta_func/ta_EXP.c
ta-lib/src/ta_func/ta_MINMAXINDEX.c
ta-lib/src/ta_func/ta_SQRT.c
ta-lib/src/ta_func/ta_FLOOR.c
ta-lib/src/ta_func/ta_CDLCONCEALBABYSWALL.c
ta-lib/src/ta_func/ta_NATR.c
ta-lib/src/ta_func/ta_CDLHARAMICROSS.c
ta-lib/src/ta_func/ta_MINUS_DM.c
ta-lib/src/ta_func/ta_LOG10.c
ta-lib/src/ta_func/ta_LINEARREG_ANGLE.c
ta-lib/src/ta_func/ta_RSI.c
ta-lib/src/ta_func/ta_CDLABANDONEDBABY.c
ta-lib/src/ta_func/ta_SAR.c
ta-lib/src/ta_func/ta_CDLBREAKAWAY.c
ta-lib/src/ta_func/ta_CDLDRAGONFLYDOJI.c
ta-lib/src/ta_func/ta_CDLHIGHWAVE.c
ta-lib/src/ta_func/ta_CDLKICKING.c
ta-lib/src/ta_func/ta_CDLDOJISTAR.c
ta-lib/src/ta_func/ta_VAR.c
ta-lib/src/ta_func/ta_CDLMATCHINGLOW.c
ta-lib/src/ta_func/ta_CDLGAPSIDESIDEWHITE.c
ta-lib/src/ta_func/ta_CDLMARUBOZU.c
ta-lib/src/ta_func/ta_AROONOSC.c
ta-lib/src/ta_func/ta_WCLPRICE.c
ta-lib/src/ta_func/ta_CDLEVENINGDOJISTAR.c
ta-lib/src/ta_func/ta_CDL3INSIDE.c
ta-lib/src/ta_func/ta_OBV.c
ta-lib/src/ta_func/ta_AROON.c
ta-lib/src/ta_func/ta_CDLBELTHOLD.c
ta-lib/src/ta_func/ta_CDLSPINNINGTOP.c
ta-lib/src/ta_func/ta_AD.c
ta-lib/src/ta_func/ta_MAX.c
ta-lib/src/ta_func/ta_CDLENGULFING.c
ta-lib/src/ta_func/ta_MINMAX.c
ta-lib/src/ta_func/ta_CDLINNECK.c
ta-lib/src/ta_func/ta_STDDEV.c
ta-lib/src/ta_func/ta_NVI.c
ta-lib/src/ta_func/ta_CDLHAMMER.c
ta-lib/src/ta_func/ta_ASIN.c
ta-lib/src/ta_func/ta_SUM.c
ta-lib/src/ta_func/ta_STOCH.c
ta-lib/src/ta_func/ta_CDLLONGLEGGEDDOJI.c
ta-lib/src/ta_func/ta_MEDPRICE.c
ta-lib/src/ta_func/ta_CDL3STARSINSOUTH.c
ta-lib/src/ta_func/ta_HT_TRENDMODE.c
ta-lib/src/ta_func/ta_BBANDS.c
ta-lib/src/ta_func/ta_CDLMORNINGSTAR.c
ta-lib/src/ta_func/ta_HT_DCPHASE.c
ta-lib/src/ta_func/ta_CDLLONGLINE.c
ta-lib/src/ta_func/ta_TAN.c
ta-lib/src/ta_func/ta_SMA.c
ta-lib/src/ta_func/ta_DX.c
ta-lib/src/ta_func/ta_MIDPOINT.c
ta-lib/src/ta_func/ta_CDL2CROWS.c
ta-lib/src/ta_func/ta_CORREL.c
ta-lib/src/ta_func/ta_CDL3BLACKCROWS.c
ta-lib/src/ta_func/ta_ADD.c
ta-lib/src/ta_func/Makefile.in
ta-lib/src/ta_func/ta_CDLTHRUSTING.c
ta-lib/src/ta_func/ta_SUB.c
ta-lib/src/ta_func/ta_CDLSTALLEDPATTERN.c
ta-lib/src/ta_func/ta_CDLTRISTAR.c
ta-lib/src/ta_func/ta_MA.c
ta-lib/src/ta_func/ta_HT_SINE.c
ta-lib/src/ta_func/ta_ACOS.c
ta-lib/src/ta_func/ta_CDLSTICKSANDWICH.c
ta-lib/src/ta_func/ta_SINH.c
ta-lib/src/ta_func/ta_utility.h
ta-lib/src/ta_func/ta_CDLSHORTLINE.c
ta-lib/src/ta_func/ta_ATAN.c
ta-lib/src/ta_func/ta_CDLADVANCEBLOCK.c
ta-lib/src/ta_func/ta_CDLKICKINGBYLENGTH.c
ta-lib/src/ta_func/ta_CDLSHOOTINGSTAR.c
ta-lib/src/ta_func/ta_ROCR.c
ta-lib/src/ta_func/ta_WMA.c
ta-lib/src/ta_func/ta_CDLDARKCLOUDCOVER.c
ta-lib/src/ta_func/ta_CDLXSIDEGAP3METHODS.c
ta-lib/src/ta_func/ta_TYPPRICE.c
ta-lib/src/ta_func/ta_CDL3WHITESOLDIERS.c
ta-lib/src/ta_func/Makefile.am
ta-lib/src/ta_func/ta_MACDEXT.c
ta-lib/src/ta_func/ta_ADX.c
ta-lib/src/ta_func/ta_PLUS_DM.c
ta-lib/src/ta_func/ta_CDLUPSIDEGAP2CROWS.c
ta-lib/src/ta_func/ta_LN.c
ta-lib/src/ta_func/ta_DEMA.c
ta-lib/src/ta_func/ta_CDL3OUTSIDE.c
ta-lib/src/ta_func/ta_CDLTASUKIGAP.c
ta-lib/src/ta_func/ta_MAMA.c
ta-lib/src/ta_func/ta_CDLMORNINGDOJISTAR.c
ta-lib/src/ta_func/ta_PLUS_DI.c
ta-lib/src/ta_func/ta_MININDEX.c
ta-lib/src/ta_func/ta_COS.c
ta-lib/src/ta_func/ta_HT_TRENDLINE.c
ta-lib/src/ta_func/ta_MIDPRICE.c
ta-lib/src/ta_func/ta_CEIL.c
ta-lib/src/ta_func/ta_TRIMA.c
ta-lib/src/ta_func/ta_CDLSEPARATINGLINES.c
ta-lib/src/ta_func/ta_ROCP.c
ta-lib/src/ta_func/ta_CDLHOMINGPIGEON.c
ta-lib/src/ta_func/ta_CDLHANGINGMAN.c
ta-lib/src/ta_func/ta_AVGPRICE.c
ta-lib/src/ta_func/ta_APO.c
ta-lib/src/ta_func/ta_CDLRISEFALL3METHODS.c
ta-lib/src/ta_func/ta_TRANGE.c
ta-lib/src/ta_func/ta_TSF.c
ta-lib/src/ta_func/ta_LINEARREG.c
ta-lib/src/ta_func/ta_PVI.c
ta-lib/src/ta_func/ta_CDLHIKKAKEMOD.c
ta-lib/src/ta_func/ta_MFI.c
ta-lib/src/ta_func/ta_CDLHARAMI.c
ta-lib/src/ta_func/ta_MACD.c
ta-lib/src/ta_func/ta_BETA.c
ta-lib/src/ta_func/ta_CDLINVERTEDHAMMER.c
ta-lib/src/ta_func/ta_LINEARREG_SLOPE.c
ta-lib/src/ta_func/ta_STOCHF.c
ta-lib/src/ta_func/ta_MIN.c
ta-lib/src/ta_func/ta_CDLIDENTICAL3CROWS.c
ta-lib/src/ta_func/ta_CDLRICKSHAWMAN.c
ta-lib/src/ta_func/ta_T3.c
ta-lib/src/ta_func/ta_CDLMATHOLD.c
ta-lib/src/ta_func/ta_CDLUNIQUE3RIVER.c
ta-lib/src/ta_func/ta_ADOSC.c
ta-lib/src/ta_func/ta_MAXINDEX.c
ta-lib/src/ta_func/ta_ULTOSC.c
ta-lib/src/ta_func/ta_TRIX.c
ta-lib/src/ta_func/ta_MOM.c
ta-lib/src/ta_func/ta_CDLDOJI.c
ta-lib/src/ta_func/ta_EMA.c
ta-lib/src/ta_func/ta_STOCHRSI.c
ta-lib/src/ta_func/ta_ROC.c
ta-lib/src/ta_func/ta_CDLEVENINGSTAR.c
ta-lib/src/ta_func/ta_CDLCOUNTERATTACK.c
ta-lib/src/ta_func/ta_LINEARREG_INTERCEPT.c
ta-lib/src/ta_func/ta_SAREXT.c
ta-lib/src/ta_func/ta_WILLR.c
ta-lib/src/ta_func/ta_MULT.c
ta-lib/src/ta_func/ta_ATR.c
ta-lib/src/ta_func/ta_BOP.c
ta-lib/src/ta_func/ta_CMO.c
ta-lib/src/ta_func/ta_CDLONNECK.c
ta-lib/src/ta_func/ta_CCI.c
ta-lib/src/ta_func/ta_CDLLADDERBOTTOM.c
ta-lib/src/ta_func/ta_HT_PHASOR.c
ta-lib/src/ta_func/ta_utility.c
ta-lib/src/ta_func/ta_PPO.c
ta-lib/src/ta_func/ta_CDLHIKKAKE.c
ta-lib/src/ta_func/ta_HT_DCPERIOD.c
ta-lib/src/ta_func/ta_CDL3LINESTRIKE.c
ta-lib/src/ta_func/ta_TEMA.c
ta-lib/src/ta_func/ta_SIN.c
ta-lib/src/ta_func/ta_MINUS_DI.c
ta-lib/src/ta_func/ta_KAMA.c
ta-lib/src/ta_func/ta_TANH.c
ta-lib/src/ta_func/ta_CDLTAKURI.c
ta-lib/src/ta_func/ta_CDLGRAVESTONEDOJI.c
ta-lib/src/ta_common/
ta-lib/src/ta_common/ta_pragma.h
ta-lib/src/ta_common/ta_magic_nb.h
ta-lib/src/ta_common/ta_retcode.csv
ta-lib/src/ta_common/Makefile.in
ta-lib/src/ta_common/Makefile.am
ta-lib/src/ta_common/ta_memory.h
ta-lib/src/ta_common/ta_version.c
ta-lib/src/ta_common/ta_global.h
ta-lib/src/ta_common/ta_global.c
ta-lib/src/ta_common/ta_retcode.c
ta-lib/src/Makefile.in
ta-lib/src/ta_abstract/
ta-lib/src/ta_abstract/frames/
ta-lib/src/ta_abstract/frames/ta_frame.c
ta-lib/src/ta_abstract/frames/ta_frame.h
ta-lib/src/ta_abstract/excel_glue.c
ta-lib/src/ta_abstract/ta_frame_priv.h
ta-lib/src/ta_abstract/ta_func_api.c
ta-lib/src/ta_abstract/Makefile.in
ta-lib/src/ta_abstract/ta_def_ui.h
ta-lib/src/ta_abstract/Makefile.am
ta-lib/src/ta_abstract/ta_abstract.c
ta-lib/src/ta_abstract/ta_group_idx.c
ta-lib/src/ta_abstract/tables/
ta-lib/src/ta_abstract/tables/table_u.c
ta-lib/src/ta_abstract/tables/table_x.c
ta-lib/src/ta_abstract/tables/table_r.c
ta-lib/src/ta_abstract/tables/table_f.c
ta-lib/src/ta_abstract/tables/table_j.c
ta-lib/src/ta_abstract/tables/table_e.c
ta-lib/src/ta_abstract/tables/table_t.c
ta-lib/src/ta_abstract/tables/table_n.c
ta-lib/src/ta_abstract/tables/table_i.c
ta-lib/src/ta_abstract/tables/table_c.c
ta-lib/src/ta_abstract/tables/table_l.c
ta-lib/src/ta_abstract/tables/table_k.c
ta-lib/src/ta_abstract/tables/table_g.c
ta-lib/src/ta_abstract/tables/table_d.c
ta-lib/src/ta_abstract/tables/table_h.c
ta-lib/src/ta_abstract/tables/table_o.c
ta-lib/src/ta_abstract/tables/table_b.c
ta-lib/src/ta_abstract/tables/table_q.c
ta-lib/src/ta_abstract/tables/table_v.c
ta-lib/src/ta_abstract/tables/table_m.c
ta-lib/src/ta_abstract/tables/table_s.c
ta-lib/src/ta_abstract/tables/table_y.c
ta-lib/src/ta_abstract/tables/table_p.c
ta-lib/src/ta_abstract/tables/table_z.c
ta-lib/src/ta_abstract/tables/table_a.c
ta-lib/src/ta_abstract/tables/table_w.c
ta-lib/src/ta_abstract/ta_def_ui.c
ta-lib/src/ta_abstract/templates/
ta-lib/src/ta_abstract/templates/ta_x.c.template
ta-lib/src/ta_abstract/templates/ta_java_defs.h.template
ta-lib/src/ta_abstract/templates/excel_glue.c.template
ta-lib/src/ta_abstract/templates/ta_group_idx.c.template
ta-lib/src/ta_abstract/templates/ta_frame.c.template
ta-lib/src/ta_abstract/templates/CoreAnnotated.java.template
ta-lib/src/ta_abstract/templates/ta_func.h.template
ta-lib/src/ta_abstract/templates/ta_frame.h.template
ta-lib/src/ta_abstract/templates/Makefile.am.template
ta-lib/src/ta_abstract/templates/ta_func_api.c.template
ta-lib/src/ta_abstract/templates/ta_func.swg.template
ta-lib/src/ta_abstract/templates/ta_retcode.c.template
ta-lib/src/ta_abstract/ta_java_defs.h
ta-lib/src/Makefile.am
ta-lib/src/tools/
ta-lib/src/tools/ta_regtest/
ta-lib/src/tools/ta_regtest/test_util.c
ta-lib/src/tools/ta_regtest/ta_test_func.h
ta-lib/src/tools/ta_regtest/test_data.c
ta-lib/src/tools/ta_regtest/ta_gDataHigh.c
ta-lib/src/tools/ta_regtest/Makefile.in
ta-lib/src/tools/ta_regtest/test_internals.c
ta-lib/src/tools/ta_regtest/Makefile.am
ta-lib/src/tools/ta_regtest/ta_regtest.c
ta-lib/src/tools/ta_regtest/ta_gDataOpen.c
ta-lib/src/tools/ta_regtest/ta_gDataClose.c
ta-lib/src/tools/ta_regtest/test_abstract.c
ta-lib/src/tools/ta_regtest/ta_test_func/
ta-lib/src/tools/ta_regtest/ta_test_func/test_bbands.c
ta-lib/src/tools/ta_regtest/ta_test_func/test_stddev.c
ta-lib/src/tools/ta_regtest/ta_test_func/test_1in_2out.c
ta-lib/src/tools/ta_regtest/ta_test_func/test_sar.c
ta-lib/src/tools/ta_regtest/ta_test_func/test_1in_1out.c
ta-lib/src/tools/ta_regtest/ta_test_func/test_trange.c
ta-lib/src/tools/ta_regtest/ta_test_func/test_macd.c
ta-lib/src/tools/ta_regtest/ta_test_func/test_po.c
ta-lib/src/tools/ta_regtest/ta_test_func/test_per_hlc.c
ta-lib/src/tools/ta_regtest/ta_test_func/test_mom.c
ta-lib/src/tools/ta_regtest/ta_test_func/test_per_ohlc.c
ta-lib/src/tools/ta_regtest/ta_test_func/test_adx.c
ta-lib/src/tools/ta_regtest/ta_test_func/test_candlestick.c
ta-lib/src/tools/ta_regtest/ta_test_func/test_rsi.c
ta-lib/src/tools/ta_regtest/ta_test_func/test_per_ema.c
ta-lib/src/tools/ta_regtest/ta_test_func/test_minmax.c
ta-lib/src/tools/ta_regtest/ta_test_func/test_per_hlcv.c
ta-lib/src/tools/ta_regtest/ta_test_func/test_per_hl.c
ta-lib/src/tools/ta_regtest/ta_test_func/test_stoch.c
ta-lib/src/tools/ta_regtest/ta_test_func/test_ma.c
ta-lib/src/tools/ta_regtest/ta_error_number.h
ta-lib/src/tools/ta_regtest/ta_test_priv.h
ta-lib/src/tools/ta_regtest/ReadMe.txt
ta-lib/src/tools/ta_regtest/ta_gDataLow.c
ta-lib/src/tools/Makefile.in
ta-lib/src/tools/Makefile.am
ta-lib/src/tools/gen_code/
ta-lib/src/tools/gen_code/java/
ta-lib/src/tools/gen_code/java/PrettyCode.java
ta-lib/src/tools/gen_code/java/Main.java
ta-lib/src/tools/gen_code/gen_code.c
ta-lib/src/tools/gen_code/Makefile.in
ta-lib/src/tools/gen_code/Makefile.am
ta-lib/src/tools/gen_code/mcpp.exe
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /usr/bin/mkdir -p
checking for gawk... no
checking for mawk... mawk
checking whether make sets $(MAKE)... yes
checking for gcc... gcc
checking for C compiler default output file name... a.out
checking whether the C compiler works... yes
checking whether we are cross compiling... no
checking for suffix of executables...
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking for style of include used by make... GNU
checking dependency style of gcc... gcc3
checking build system type... x86_64-unknown-linux-gnu
checking host system type... x86_64-unknown-linux-gnu
checking for a sed that does not truncate output... /usr/bin/sed
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for ld used by gcc... /usr/bin/ld
checking if the linker (/usr/bin/ld) is GNU ld... yes
checking for /usr/bin/ld option to reload object files... -r
checking for BSD-compatible nm... /usr/bin/nm -B
checking whether ln -s works... yes
checking how to recognise dependent libraries... pass_all
checking how to run the C preprocessor... gcc -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking dlfcn.h usability... yes
checking dlfcn.h presence... yes
checking for dlfcn.h... yes
checking for g++... g++
checking whether we are using the GNU C++ compiler... yes
checking whether g++ accepts -g... yes
checking dependency style of g++... gcc3
checking how to run the C++ preprocessor... g++ -E
checking for g77... no
checking for xlf... no
checking for f77... f77
checking whether we are using the GNU Fortran 77 compiler... yes
checking whether f77 accepts -g... yes
checking the maximum length of command line arguments... 32768
checking command to parse /usr/bin/nm -B output from gcc object... ok
checking for objdir... .libs
checking for ar... ar
checking for ranlib... ranlib
checking for strip... strip
checking if gcc supports -fno-rtti -fno-exceptions... no
checking for gcc option to produce PIC... -fPIC
checking if gcc PIC flag -fPIC works... yes
checking if gcc static flag -static works... yes
checking if gcc supports -c -o file.o... yes
checking whether the gcc linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking whether -lc should be explicitly linked in... no
checking dynamic linker characteristics... GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... yes
configure: creating libtool
appending configuration tag "CXX" to libtool
checking for ld used by g++... /usr/bin/ld -m elf_x86_64
checking if the linker (/usr/bin/ld -m elf_x86_64) is GNU ld... yes
checking whether the g++ linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking for g++ option to produce PIC... -fPIC
checking if g++ PIC flag -fPIC works... yes
checking if g++ static flag -static works... yes
checking if g++ supports -c -o file.o... yes
checking whether the g++ linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking dynamic linker characteristics... GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
appending configuration tag "F77" to libtool
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... yes
checking for f77 option to produce PIC... -fPIC
checking if f77 PIC flag -fPIC works... yes
checking if f77 static flag -static works... yes
checking if f77 supports -c -o file.o... yes
checking whether the f77 linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking dynamic linker characteristics... GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking for dlopen in -ldl... yes
checking for pthread_create in -lpthread... yes
checking for ANSI C header files... (cached) yes
checking float.h usability... yes
checking float.h presence... yes
checking for float.h... yes
checking for inttypes.h... (cached) yes
checking limits.h usability... yes
checking limits.h presence... yes
checking for limits.h... yes
checking locale.h usability... yes
checking locale.h presence... yes
checking for locale.h... yes
checking stddef.h usability... yes
checking stddef.h presence... yes
checking for stddef.h... yes
checking for stdint.h... (cached) yes
checking for stdlib.h... (cached) yes
checking for string.h... (cached) yes
checking for unistd.h... (cached) yes
checking wchar.h usability... yes
checking wchar.h presence... yes
checking for wchar.h... yes
checking wctype.h usability... yes
checking wctype.h presence... yes
checking for wctype.h... yes
checking for an ANSI C-conforming const... yes
checking for size_t... yes
checking whether struct tm is in sys/time.h or time.h... time.h
checking for working volatile... yes
checking for ptrdiff_t... yes
checking return type of signal handlers... void
checking for working strcoll... yes
checking for strftime... yes
checking for working strtod... yes
checking for vprintf... yes
checking for _doprnt... no
checking for floor... no
checking for isascii... yes
checking for localeconv... yes
checking for mblen... yes
checking for memmove... yes
checking for memset... yes
checking for modf... yes
checking for pow... no
checking for sqrt... no
checking for strcasecmp... yes
checking for strchr... yes
checking for strerror... yes
checking for strncasecmp... yes
checking for strrchr... yes
checking for strstr... yes
checking for strtol... yes
checking for strtoul... yes
configure: creating ./config.status
config.status: creating Makefile
config.status: creating src/Makefile
config.status: creating src/ta_abstract/Makefile
config.status: creating src/ta_common/Makefile
config.status: creating src/ta_func/Makefile
config.status: creating src/tools/Makefile
config.status: creating src/tools/gen_code/Makefile
config.status: creating src/tools/ta_regtest/Makefile
config.status: creating ta-lib-config
config.status: creating ta-lib.spec
config.status: creating ta-lib.dpkg
config.status: creating include/ta_config.h
config.status: executing depfiles commands
Making all in src
make[1]: Entering directory '/content/ta-lib/src'
Making all in ta_abstract
make[2]: Entering directory '/content/ta-lib/src/ta_abstract'
/bin/bash ../../libtool --tag=CC   --mode=compile gcc -DHAVE_CONFIG_H -I. -I../../include  -I../ta_common/ -Iframes/   -g -O2 -MT libta_abstract_la-ta_group_idx.lo -MD -MP -MF .deps/libta_abstract_la-ta_group_idx.Tpo -c -o libta_abstract_la-ta_group_idx.lo `test -f 'ta_group_idx.c' || echo './'`ta_group_idx.c
mkdir .libs
 gcc -DHAVE_CONFIG_H -I. -I../../include -I../ta_common/ -Iframes/ -g -O2 -MT libta_abstract_la-ta_group_idx.lo -MD -MP -MF .deps/libta_abstract_la-ta_group_idx.Tpo -c ta_group_idx.c  -fPIC -DPIC -o .libs/libta_abstract_la-ta_group_idx.o
 gcc -DHAVE_CONFIG_H -I. -I../../include -I../ta_common/ -Iframes/ -g -O2 -MT libta_abstract_la-ta_group_idx.lo -MD -MP -MF .deps/libta_abstract_la-ta_group_idx.Tpo -c ta_group_idx.c -o libta_abstract_la-ta_group_idx.o >/dev/null 2>&1
mv -f .deps/libta_abstract_la-ta_group_idx.Tpo .deps/libta_abstract_la-ta_group_idx.Plo
/bin/bash ../../libtool --tag=CC   --mode=compile gcc -DHAVE_CONFIG_H -I. -I../../include  -I../ta_common/ -Iframes/   -g -O2 -MT libta_abstract_la-ta_def_ui.lo -MD -MP -MF .deps/libta_abstract_la-ta_def_ui.Tpo -c -o libta_abstract_la-ta_def_ui.lo `test -f 'ta_def_ui.c' || echo './'`ta_def_ui.c
 gcc -DHAVE_CONFIG_H -I. -I../../include -I../ta_common/ -Iframes/ -g -O2 -MT libta_abstract_la-ta_def_ui.lo -MD -MP -MF .deps/libta_abstract_la-ta_def_ui.Tpo -c ta_def_ui.c  -fPIC -DPIC -o .libs/libta_abstract_la-ta_def_ui.o
 gcc -DHAVE_CONFIG_H -I. -I../../include -I../ta_common/ -Iframes/ -g -O2 -MT libta_abstract_la-ta_def_ui.lo -MD -MP -MF .deps/libta_abstract_la-ta_def_ui.Tpo -c ta_def_ui.c -o libta_abstract_la-ta_def_ui.o >/dev/null 2>&1
mv -f .deps/libta_abstract_la-ta_def_ui.Tpo .deps/libta_abstract_la-ta_def_ui.Plo

In [ ]:
!pip install scikit-tree

Collecting scikit-tree
  Downloading scikit_tree-0.8.0-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (9.9 kB)
Requirement already satisfied: numpy>=1.25.0 in /usr/local/lib/python3.12/dist-packages (from scikit-tree) (2.0.2)
Requirement already satisfied: scipy>=1.5.0 in /usr/local/lib/python3.12/dist-packages (from scikit-tree) (1.16.3)
Requirement already satisfied: scikit-learn>=1.4.1 in /usr/local/lib/python3.12/dist-packages (from scikit-tree) (1.6.1)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn>=1.4.1->scikit-tree) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn>=1.4.1->scikit-tree) (3.6.0)
Downloading scikit_tree-0.8.0-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (2.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.5/2.5 MB 14.5 MB/s eta 0:00:00
Installing collected packages: scikit-tree
Successfully installed scikit-tree-0.8.0

In [ ]:
import talib as ta
import random
import time
import datetime as dt
from datetime import datetime, timedelta
import numpy as np
import yfinance as yf
import pandas as pd
from warnings import simplefilter
simplefilter(action="ignore", category=pd.errors.PerformanceWarning) #ignores "Dataframe is highly fragmented" warning.
from sklearn import preprocessing
from sklearn.model_selection import train_test_split,cross_val_score
from sklearn.metrics import confusion_matrix, classification_report, roc_auc_score,mean_absolute_error, mean_absolute_percentage_error, r2_score, precision_score, accuracy_score
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sktree import tree
from sklearn.ensemble import (AdaBoostClassifier, RandomForestClassifier,
                              StackingClassifier, GradientBoostingClassifier,
                              ExtraTreesClassifier, BaggingClassifier, VotingClassifier, IsolationForest)
from sklearn.svm import SVC
from sklearn.neural_network import MLPClassifier, MLPRegressor
# Import regressors
from xgboost import XGBRegressor
from sklearn.ensemble import GradientBoostingRegressor, RandomForestRegressor
from sklearn.linear_model import LinearRegression
from sklearn.feature_selection import RFECV, SelectFromModel
from matplotlib import pyplot as plt
import math
import lightgbm as lgb
from dateutil.relativedelta import relativedelta

#Functions (~10s)

In [ ]:
def change_days(date_str, days):
    import datetime as dt
    date = dt.datetime.strptime(date_str, "%Y-%m-%d")

    new_date = date + timedelta(days=days)

    return new_date.strftime("%Y-%m-%d")

def change_months(date_str, monthss):
  import datetime as dt
  date_obj = datetime.strptime(date_str, "%Y-%m-%d")

  new_date = date_obj + relativedelta(months=monthss)

  return new_date.strftime("%Y-%m-%d")

def data(stock, startdate, enddate, shuffle=True):

  #push end date back a month to increase viable data(non-NaN) to right before dates tested
  enddate = enddate

  stock_data = yf.Ticker(stock).history(start = startdate, end=enddate)

  #Closing prices on previous days:
  for i in range(1, 60):
          stock_data[f"Close -{i}d"] = stock_data["Close"].shift(i)
          stock_data[f"High -{i}d"] = stock_data["High"].shift(i)
          stock_data[f"Low -{i}d"] = stock_data["Low"].shift(i)


  #Technical indicators
  stock_data['BB_upper'], stock_data['BB_middle'], stock_data['BB_lower'] = ta.BBANDS(stock_data['Close'], timeperiod=20, nbdevup=0, nbdevdn=2, matype=0)
  stock_data['KAMA'] = ta.KAMA(stock_data['Close'], timeperiod=30)
  stock_data['MA'] = ta.MA(stock_data['Close'], timeperiod=30)
  stock_data['TRIMA'] = ta.TRIMA(stock_data['Close'], timeperiod=30)
  stock_data['ADXR'] = ta.ADXR(stock_data['High'], stock_data['Low'], stock_data['Close'], timeperiod=14)
  stock_data['APO'] = ta.APO(stock_data['Close'], fastperiod=12, slowperiod=26)
  stock_data['MINUS_DI'] = ta.MINUS_DI(stock_data['High'], stock_data['Low'], stock_data['Close'], timeperiod=14)
  stock_data['MINUS_DM'] = ta.MINUS_DM(stock_data['High'], stock_data['Low'], timeperiod=14)
  stock_data['PPO'] = ta.PPO(stock_data['Close'], fastperiod=12, slowperiod=26, matype=0)
  stock_data['ADOSC'] = ta.ADOSC(stock_data['High'], stock_data['Low'], stock_data['Close'], stock_data['Volume'], fastperiod=3, slowperiod=10)
  stock_data['HT_DCPERIOD'] = ta.HT_DCPERIOD(stock_data['Close'])
  stock_data['TYPPRICE'] = ta.TYPPRICE(stock_data['High'], stock_data['Low'], stock_data['Close'])
  stock_data['WCLPRICE'] = ta.WCLPRICE(stock_data['High'], stock_data['Low'], stock_data['Close'])
  stock_data['DEMA'] = ta.DEMA(stock_data['Close'], timeperiod=30)##
  stock_data["EMA"] = ta.EMA(stock_data["Close"], timeperiod=14)  ##
  stock_data['HT_TRENDLINE'] = ta.HT_TRENDLINE(stock_data['Close'])##
  stock_data['MIDPOINT'] = ta.MIDPOINT(stock_data['Close'], timeperiod=14)##
  stock_data['ADX'] = ta.ADX(stock_data["High"], stock_data["Low"], stock_data["Close"], timeperiod=14)  ##
  stock_data["RSI"] = ta.RSI(stock_data["Close"], timeperiod=14)##
  stock_data["OBV"] = ta.OBV(stock_data["Close"], stock_data["Volume"])##
  stock_data["MIDPOINT_30"] = stock_data["MIDPOINT"].pct_change(periods=30)
  stock_data['SAR'] = ta.SAR(stock_data['High'], stock_data['Low'], acceleration=0.02, maximum=0.2)
  stock_data['macd'], stock_data['macd_signal'], stock_data['macd_diff'] = ta.MACD(stock_data['Close'], fastperiod=12, slowperiod=26, signalperiod=9)
  stock_data["bband_width"] = stock_data['BB_upper'] - stock_data['BB_lower']
  stock_data['stochastic oscillator %K'], stock_data['stochastic oscillator %D'] = ta.STOCH(stock_data['High'], stock_data['Low'], stock_data['Close'], fastk_period=5, slowk_period=3, slowk_matype=0, slowd_period=3, slowd_matype=0)
  stock_data["atr"] = ta.ATR(stock_data["High"], stock_data["Low"], stock_data["Close"], timeperiod=14)
  stock_data["SMA"] = ta.SMA(stock_data["Close"], timeperiod=14)
  stock_data["ROC"] = ta.ROC(stock_data["Close"], timeperiod=12)
  stock_data["CCI"] = ta.CCI(stock_data["High"], stock_data["Low"], stock_data["Close"], timeperiod=14)
  stock_data["AD"] = ta.AD(stock_data["High"], stock_data["Low"], stock_data["Close"], stock_data["Volume"])
  stock_data["NATR"] = ta.NATR(stock_data["High"], stock_data["Low"], stock_data["Close"], timeperiod=14)
  stock_data["TRIX"] = ta.TRIX(stock_data["Close"],timeperiod=30)

  #5 day
  stock_data['BB_upper_5'], stock_data['BB_middle_5'], stock_data['BB_lower_5'] = ta.BBANDS(stock_data['Close -5d'], timeperiod=5, nbdevup=0, nbdevdn=2, matype=0)
  stock_data["bband_width_5"] = stock_data['BB_upper_5'] - stock_data['BB_lower_5']
  stock_data['KAMA_5'] = ta.KAMA(stock_data['Close -5d'], timeperiod=5)
  stock_data['MA_5'] = ta.MA(stock_data['Close -5d'], timeperiod=5)
  stock_data['TRIMA_5'] = ta.TRIMA(stock_data['Close -5d'], timeperiod=5)
  stock_data['ADXR_5'] = ta.ADXR(stock_data['High -5d'], stock_data['Low -5d'], stock_data['Close -5d'], timeperiod=5)
  stock_data['MINUS_DI_5'] = ta.MINUS_DI(stock_data['High -5d'], stock_data['Low -5d'], stock_data['Close -5d'], timeperiod=5)
  stock_data['MINUS_DM_5'] = ta.MINUS_DM(stock_data['High -5d'], stock_data['Low -5d'], timeperiod=5)
  stock_data['DEMA_5'] = ta.DEMA(stock_data['Close -5d'], timeperiod=5)
  stock_data["EMA_5"] = ta.EMA(stock_data["Close -5d"], timeperiod=5)
  stock_data['HT_TRENDLINE_5'] = stock_data["HT_TRENDLINE"].pct_change(periods=5)
  stock_data['MIDPOINT_5'] = ta.MIDPOINT(stock_data['Close -5d'], timeperiod=5)
  stock_data['ADX_5'] = ta.ADX(stock_data["High -5d"], stock_data["Low -5d"], stock_data["Close -5d"], timeperiod=5)
  stock_data["RSI_5"] = ta.RSI(stock_data["Close -5d"], timeperiod=5)
  stock_data["MIDPOINT_30_5"] = stock_data["MIDPOINT_5"].pct_change(periods=5)
  stock_data["atr_5"] = ta.ATR(stock_data["High -5d"], stock_data["Low -5d"], stock_data["Close -5d"], timeperiod=5)
  stock_data["SMA_5"] = ta.SMA(stock_data["Close -5d"], timeperiod=5)
  stock_data["ROC_5"] = ta.ROC(stock_data["Close -5d"], timeperiod=5)
  stock_data["CCI_5"] = ta.CCI(stock_data["High -5d"], stock_data["Low -5d"], stock_data["Close -5d"], timeperiod=5)
  stock_data["NATR_5"] = ta.NATR(stock_data["High -5d"], stock_data["Low -5d"], stock_data["Close -5d"], timeperiod=5)
  stock_data["TRIX_5"] = ta.TRIX(stock_data["Close -5d"], timeperiod=5)

  #10 day
  stock_data['BB_upper_10'], stock_data['BB_middle_10'], stock_data['BB_lower_10'] = ta.BBANDS(stock_data['Close -10d'], timeperiod=5, nbdevup=0, nbdevdn=2, matype=0)
  stock_data["bband_width_10"] = stock_data['BB_upper_10'] - stock_data['BB_lower_10']
  stock_data['KAMA_10'] = ta.KAMA(stock_data['Close -10d'], timeperiod=5)
  stock_data['MA_10'] = ta.MA(stock_data['Close -10d'], timeperiod=5)
  stock_data['TRIMA_10'] = ta.TRIMA(stock_data['Close -10d'], timeperiod=5)
  stock_data['ADXR_10'] = ta.ADXR(stock_data['High -10d'], stock_data['Low -10d'], stock_data['Close -10d'], timeperiod=5)
  stock_data['MINUS_DI_10'] = ta.MINUS_DI(stock_data['High -10d'], stock_data['Low -10d'], stock_data['Close -10d'], timeperiod=5)
  stock_data['MINUS_DM_10'] = ta.MINUS_DM(stock_data['High -10d'], stock_data['Low -10d'], timeperiod=5)
  stock_data['DEMA_10'] = ta.DEMA(stock_data['Close -10d'], timeperiod=5)
  stock_data["EMA_10"] = ta.EMA(stock_data["Close -10d"], timeperiod=5)
  stock_data['HT_TRENDLINE_10'] = stock_data["HT_TRENDLINE"].pct_change(periods=5)
  stock_data['MIDPOINT_10'] = ta.MIDPOINT(stock_data['Close -10d'], timeperiod=5)
  stock_data['ADX_10'] = ta.ADX(stock_data["High -10d"], stock_data["Low -10d"], stock_data["Close -10d"], timeperiod=5)
  stock_data["RSI_10"] = ta.RSI(stock_data["Close -10d"], timeperiod=5)
  stock_data["MIDPOINT_30_10"] = stock_data["MIDPOINT_10"].pct_change(periods=5)
  stock_data["atr_10"] = ta.ATR(stock_data["High -10d"], stock_data["Low -10d"], stock_data["Close -10d"], timeperiod=5)
  stock_data["SMA_10"] = ta.SMA(stock_data["Close -10d"], timeperiod=5)
  stock_data["ROC_10"] = ta.ROC(stock_data["Close -10d"], timeperiod=5)
  stock_data["CCI_10"] = ta.CCI(stock_data["High -10d"], stock_data["Low -10d"], stock_data["Close -10d"], timeperiod=5)
  stock_data["NATR_10"] = ta.NATR(stock_data["High -10d"], stock_data["Low -10d"], stock_data["Close -10d"], timeperiod=5)
  stock_data["TRIX_10"] = ta.TRIX(stock_data["Close -10d"], timeperiod=5)

  #30 day
  stock_data['BB_upper_30'], stock_data['BB_middle_30'], stock_data['BB_lower_30'] = ta.BBANDS(stock_data['Close -30d'], timeperiod=5, nbdevup=0, nbdevdn=2, matype=0)
  stock_data["bband_width_30"] = stock_data['BB_upper_30'] - stock_data['BB_lower_30']
  stock_data['KAMA_30'] = ta.KAMA(stock_data['Close -30d'], timeperiod=5)
  stock_data['MA_30'] = ta.MA(stock_data['Close -30d'], timeperiod=5)
  stock_data['TRIMA_30'] = ta.TRIMA(stock_data['Close -30d'], timeperiod=5)
  stock_data['ADXR_30'] = ta.ADXR(stock_data['High -30d'], stock_data['Low -30d'], stock_data['Close -30d'], timeperiod=5)
  stock_data['MINUS_DI_30'] = ta.MINUS_DI(stock_data['High -30d'], stock_data['Low -30d'], stock_data['Close -30d'], timeperiod=5)
  stock_data['MINUS_DM_30'] = ta.MINUS_DM(stock_data['High -30d'], stock_data['Low -30d'], timeperiod=5)
  stock_data['DEMA_30'] = ta.DEMA(stock_data['Close -30d'], timeperiod=5)
  stock_data["EMA_30"] = ta.EMA(stock_data["Close -30d"], timeperiod=5)
  stock_data['HT_TRENDLINE_30'] = stock_data["HT_TRENDLINE"].pct_change(periods=5)
  stock_data['MIDPOINT_30'] = ta.MIDPOINT(stock_data['Close -30d'], timeperiod=5)
  stock_data['ADX_30'] = ta.ADX(stock_data["High -30d"], stock_data["Low -30d"], stock_data["Close -30d"], timeperiod=5)
  stock_data["RSI_30"] = ta.RSI(stock_data["Close -30d"], timeperiod=5)
  stock_data["MIDPOINT_30_30"] = stock_data["MIDPOINT_30"].pct_change(periods=5)
  stock_data["atr_30"] = ta.ATR(stock_data["High -30d"], stock_data["Low -30d"], stock_data["Close -30d"], timeperiod=5)
  stock_data["SMA_30"] = ta.SMA(stock_data["Close -30d"], timeperiod=5)
  stock_data["ROC_30"] = ta.ROC(stock_data["Close -30d"], timeperiod=5)
  stock_data["CCI_30"] = ta.CCI(stock_data["High -30d"], stock_data["Low -30d"], stock_data["Close -30d"], timeperiod=5)
  stock_data["NATR_30"] = ta.NATR(stock_data["High -30d"], stock_data["Low -30d"], stock_data["Close -30d"], timeperiod=5)
  stock_data["TRIX_30"] = ta.TRIX(stock_data["Close -30d"], timeperiod=5)

  #Creating the label
  x = yf.Ticker(stock).history(start = change_months(startdate, 1), end = change_months(enddate, 1))["Close"]
  l = x.tolist()

  if stock_data.shape[0] > len(l):
    nan_count = stock_data.shape[0] - len(l)
    for i in range(nan_count):
      l.append(float('nan'))

  if stock_data.shape[0] < len(l):
    q = len(l)-stock_data.shape[0]
    for i in range(q):
      l.remove(l[-1])


  stock_data["future"] = l
  stock_data["future_pct_change"] = (stock_data["future"]-stock_data["Close"])/stock_data["Close"]
  stock_data["label"] = np.where(stock_data["future_pct_change"] > 0.05, 1,
                          np.where(stock_data["future_pct_change"] < -0.05, -1, 0)
                      )


  # Replace infinite values with NaN
  stock_data[np.isinf(stock_data)] = np.nan
  # Drop all Nan values
  stock_data = stock_data.dropna()


  stock_data = stock_data.drop(columns=["future","future_change"])#"one_mo_change"

  if shuffle == True:
    #shuffling the data
    stock_data = stock_data.sample(frac=1, random_state = 1)

  label = pd.DataFrame()
  label["label"] = stock_data.pop("label")

  return stock_data, label

#📌 pred_data function requires proof reading to ensure data created is accurate.
def pred_data(stock,end_,):
  start_ = change_days(end_, -150)
  pred = yf.Ticker(stock).history(start=start_, end=end_)


  for i in range(1, 60):
      pred[f"Close -{i}d"] = pred["Close"].shift(i)
      pred[f"High -{i}d"] = pred["High"].shift(i)
      pred[f"Low -{i}d"] = pred["Low"].shift(i)

  #Technical indicators
  pred['BB_upper'], pred['BB_middle'], pred['BB_lower'] = ta.BBANDS(pred['Close'], timeperiod=20, nbdevup=0, nbdevdn=2, matype=0)
  pred['KAMA'] = ta.KAMA(pred['Close'], timeperiod=30)
  pred['MA'] = ta.MA(pred['Close'], timeperiod=30)
  pred['TRIMA'] = ta.TRIMA(pred['Close'], timeperiod=30)
  pred['ADXR'] = ta.ADXR(pred['High'], pred['Low'], pred['Close'], timeperiod=14)
  pred['APO'] = ta.APO(pred['Close'], fastperiod=12, slowperiod=26)
  pred['MINUS_DI'] = ta.MINUS_DI(pred['High'], pred['Low'], pred['Close'], timeperiod=14)
  pred['MINUS_DM'] = ta.MINUS_DM(pred['High'], pred['Low'], timeperiod=14)
  pred['PPO'] = ta.PPO(pred['Close'], fastperiod=12, slowperiod=26, matype=0)
  pred['ADOSC'] = ta.ADOSC(pred['High'], pred['Low'], pred['Close'], pred['Volume'], fastperiod=3, slowperiod=10)
  pred['HT_DCPERIOD'] = ta.HT_DCPERIOD(pred['Close'])
  pred['TYPPRICE'] = ta.TYPPRICE(pred['High'], pred['Low'], pred['Close'])
  pred['WCLPRICE'] = ta.WCLPRICE(pred['High'], pred['Low'], pred['Close'])
  pred['DEMA'] = ta.DEMA(pred['Close'], timeperiod=30)##
  pred["EMA"] = ta.EMA(pred["Close"], timeperiod=14)  ##
  pred['HT_TRENDLINE'] = ta.HT_TRENDLINE(pred['Close'])##
  pred['MIDPOINT'] = ta.MIDPOINT(pred['Close'], timeperiod=14)##
  pred['ADX'] = ta.ADX(pred["High"], pred["Low"], pred["Close"], timeperiod=14)  ##
  pred["RSI"] = ta.RSI(pred["Close"], timeperiod=14)##
  pred["OBV"] = ta.OBV(pred["Close"], pred["Volume"])##
  pred["MIDPOINT_30"] = pred["MIDPOINT"].pct_change(periods=30)
  pred['SAR'] = ta.SAR(pred['High'], pred['Low'], acceleration=0.02, maximum=0.2)
  pred['macd'], pred['macd_signal'], pred['macd_diff'] = ta.MACD(pred['Close'], fastperiod=12, slowperiod=26, signalperiod=9)
  pred["bband_width"] = pred['BB_upper'] - pred['BB_lower']
  pred['stochastic oscillator %K'], pred['stochastic oscillator %D'] = ta.STOCH(pred['High'], pred['Low'], pred['Close'], fastk_period=5, slowk_period=3, slowk_matype=0, slowd_period=3, slowd_matype=0)
  pred["atr"] = ta.ATR(pred["High"], pred["Low"], pred["Close"], timeperiod=14)
  pred["SMA"] = ta.SMA(pred["Close"], timeperiod=14)
  pred["ROC"] = ta.ROC(pred["Close"], timeperiod=12)
  pred["CCI"] = ta.CCI(pred["High"], pred["Low"], pred["Close"], timeperiod=14)
  pred["AD"] = ta.AD(pred["High"], pred["Low"], pred["Close"], pred["Volume"])
  pred["NATR"] = ta.NATR(pred["High"], pred["Low"], pred["Close"], timeperiod=14)
  pred["TRIX"] = ta.TRIX(pred["Close"],timeperiod=30)

  #5 day
  pred['BB_upper_5'], pred['BB_middle_5'], pred['BB_lower_5'] = ta.BBANDS(pred['Close -5d'], timeperiod=5, nbdevup=0, nbdevdn=2, matype=0)
  pred["bband_width_5"] = pred['BB_upper_5'] - pred['BB_lower_5']
  pred['KAMA_5'] = ta.KAMA(pred['Close -5d'], timeperiod=5)
  pred['MA_5'] = ta.MA(pred['Close -5d'], timeperiod=5)
  pred['TRIMA_5'] = ta.TRIMA(pred['Close -5d'], timeperiod=5)
  pred['ADXR_5'] = ta.ADXR(pred['High -5d'], pred['Low -5d'], pred['Close -5d'], timeperiod=5)
  pred['MINUS_DI_5'] = ta.MINUS_DI(pred['High -5d'], pred['Low -5d'], pred['Close -5d'], timeperiod=5)
  pred['MINUS_DM_5'] = ta.MINUS_DM(pred['High -5d'], pred['Low -5d'], timeperiod=5)
  pred['DEMA_5'] = ta.DEMA(pred['Close -5d'], timeperiod=5)
  pred["EMA_5"] = ta.EMA(pred["Close -5d"], timeperiod=5)
  pred['HT_TRENDLINE_5'] = pred["HT_TRENDLINE"].pct_change(periods=5)
  pred['MIDPOINT_5'] = ta.MIDPOINT(pred['Close -5d'], timeperiod=5)
  pred['ADX_5'] = ta.ADX(pred["High -5d"], pred["Low -5d"], pred["Close -5d"], timeperiod=5)
  pred["RSI_5"] = ta.RSI(pred["Close -5d"], timeperiod=5)
  pred["MIDPOINT_30_5"] = pred["MIDPOINT_5"].pct_change(periods=5)
  pred["atr_5"] = ta.ATR(pred["High -5d"], pred["Low -5d"], pred["Close -5d"], timeperiod=5)
  pred["SMA_5"] = ta.SMA(pred["Close -5d"], timeperiod=5)
  pred["ROC_5"] = ta.ROC(pred["Close -5d"], timeperiod=5)
  pred["CCI_5"] = ta.CCI(pred["High -5d"], pred["Low -5d"], pred["Close -5d"], timeperiod=5)
  pred["NATR_5"] = ta.NATR(pred["High -5d"], pred["Low -5d"], pred["Close -5d"], timeperiod=5)
  pred["TRIX_5"] = ta.TRIX(pred["Close -5d"], timeperiod=5)

  #10 day
  pred['BB_upper_10'], pred['BB_middle_10'], pred['BB_lower_10'] = ta.BBANDS(pred['Close -10d'], timeperiod=5, nbdevup=0, nbdevdn=2, matype=0)
  pred["bband_width_10"] = pred['BB_upper_10'] - pred['BB_lower_10']
  pred['KAMA_10'] = ta.KAMA(pred['Close -10d'], timeperiod=5)
  pred['MA_10'] = ta.MA(pred['Close -10d'], timeperiod=5)
  pred['TRIMA_10'] = ta.TRIMA(pred['Close -10d'], timeperiod=5)
  pred['ADXR_10'] = ta.ADXR(pred['High -10d'], pred['Low -10d'], pred['Close -10d'], timeperiod=5)
  pred['MINUS_DI_10'] = ta.MINUS_DI(pred['High -10d'], pred['Low -10d'], pred['Close -10d'], timeperiod=5)
  pred['MINUS_DM_10'] = ta.MINUS_DM(pred['High -10d'], pred['Low -10d'], timeperiod=5)
  pred['DEMA_10'] = ta.DEMA(pred['Close -10d'], timeperiod=5)
  pred["EMA_10"] = ta.EMA(pred["Close -10d"], timeperiod=5)
  pred['HT_TRENDLINE_10'] = pred["HT_TRENDLINE"].pct_change(periods=5)
  pred['MIDPOINT_10'] = ta.MIDPOINT(pred['Close -10d'], timeperiod=5)
  pred['ADX_10'] = ta.ADX(pred["High -10d"], pred["Low -10d"], pred["Close -10d"], timeperiod=5)
  pred["RSI_10"] = ta.RSI(pred["Close -10d"], timeperiod=5)
  pred["MIDPOINT_30_10"] = pred["MIDPOINT_10"].pct_change(periods=5)
  pred["atr_10"] = ta.ATR(pred["High -10d"], pred["Low -10d"], pred["Close -10d"], timeperiod=5)
  pred["SMA_10"] = ta.SMA(pred["Close -10d"], timeperiod=5)
  pred["ROC_10"] = ta.ROC(pred["Close -10d"], timeperiod=5)
  pred["CCI_10"] = ta.CCI(pred["High -10d"], pred["Low -10d"], pred["Close -10d"], timeperiod=5)
  pred["NATR_10"] = ta.NATR(pred["High -10d"], pred["Low -10d"], pred["Close -10d"], timeperiod=5)
  pred["TRIX_10"] = ta.TRIX(pred["Close -10d"], timeperiod=5)

  #30 day
  pred['BB_upper_30'], pred['BB_middle_30'], pred['BB_lower_30'] = ta.BBANDS(pred['Close -30d'], timeperiod=5, nbdevup=0, nbdevdn=2, matype=0)
  pred["bband_width_30"] = pred['BB_upper_30'] - pred['BB_lower_30']
  pred['KAMA_30'] = ta.KAMA(pred['Close -30d'], timeperiod=5)
  pred['MA_30'] = ta.MA(pred['Close -30d'], timeperiod=5)
  pred['TRIMA_30'] = ta.TRIMA(pred['Close -30d'], timeperiod=5)
  pred['ADXR_30'] = ta.ADXR(pred['High -30d'], pred['Low -30d'], pred['Close -30d'], timeperiod=5)
  pred['MINUS_DI_30'] = ta.MINUS_DI(pred['High -30d'], pred['Low -30d'], pred['Close -30d'], timeperiod=5)
  pred['MINUS_DM_30'] = ta.MINUS_DM(pred['High -30d'], pred['Low -30d'], timeperiod=5)
  pred['DEMA_30'] = ta.DEMA(pred['Close -30d'], timeperiod=5)
  pred["EMA_30"] = ta.EMA(pred["Close -30d"], timeperiod=5)
  pred['HT_TRENDLINE_30'] = pred["HT_TRENDLINE"].pct_change(periods=5)
  pred['MIDPOINT_30'] = ta.MIDPOINT(pred['Close -30d'], timeperiod=5)
  pred['ADX_30'] = ta.ADX(pred["High -30d"], pred["Low -30d"], pred["Close -30d"], timeperiod=5)
  pred["RSI_30"] = ta.RSI(pred["Close -30d"], timeperiod=5)
  pred["MIDPOINT_30_30"] = pred["MIDPOINT_30"].pct_change(periods=5)
  pred["atr_30"] = ta.ATR(pred["High -30d"], pred["Low -30d"], pred["Close -30d"], timeperiod=5)
  pred["SMA_30"] = ta.SMA(pred["Close -30d"], timeperiod=5)
  pred["ROC_30"] = ta.ROC(pred["Close -30d"], timeperiod=5)
  pred["CCI_30"] = ta.CCI(pred["High -30d"], pred["Low -30d"], pred["Close -30d"], timeperiod=5)
  pred["NATR_30"] = ta.NATR(pred["High -30d"], pred["Low -30d"], pred["Close -30d"], timeperiod=5)
  pred["TRIX_30"] = ta.TRIX(pred["Close -30d"], timeperiod=5)

  pred=pred.dropna()
  return pred.tail(1)

#tie-breaking
def tie_break(l, epsilon=0.001):
    seen = {}
    for i, x in enumerate(l):
        if x in seen:
            count = seen[x]
            l[i] += epsilon * count
            seen[x] += 1
        else:
            seen[x] = 1
    return l

def backtest(stock, date, mo_or_wk):#function will return how much the stock price changed in the coming month/week

  if mo_or_wk == "mo":
    enddate = change_months(date, 1)

    initial_price = yf.Ticker(stock).history(start = change_days(date, -5), end = date).tail(1)
    new_price = yf.Ticker(stock).history(start = date, end = enddate).tail(1)
    print(f'''{stock}
      initial close: {initial_price["Close"]},
      new close: {new_price["Close"]}
      ''')

    pct_change = (float(new_price["Close"])-float(initial_price["Close"]))/float(initial_price["Close"])
    print(f"💎 {stock} CHANGE:", pct_change, "\n")
    return pct_change

  elif mo_or_wk == "wk":
    enddate = change_days(date, 7)
    #print(enddate)
    #print(startdate)

    initial_price = yf.Ticker(stock).history(start = change_days(date, -5), end = date).tail(1)
    new_price = yf.Ticker(stock).history(start = date, end = enddate).tail(1)
    #print(initial_price["Close"], new_price["Close"])

    pct_change = (float(new_price["Close"])-float(initial_price["Close"]))/float(initial_price["Close"])

    return pct_change

def backtest_exit_rules(stock, date):#function will return how much the stock price changed in the coming month with exit rules
  enddate = change_months(date, 1)
  print(f"[------=====⬜◼️⬜◼️⬜ Backtesting {stock} ⬜◼️⬜◼️⬜=====--------]")

  initial_price = yf.Ticker(stock).history(start = change_days(date, -5), end = date).tail(1)
  new_price = yf.Ticker(stock).history(start = date, end = enddate).tail(1)

  order = new_price["Close"].to_list()
  max = float(initial_price["Close"].iloc[0])*1.1
  min = float(initial_price["Close"].iloc[0])*0.9
  pct_change = (float(new_price["Close"].iloc[0])-float(initial_price["Close"].iloc[0]))/float(initial_price["Close"].iloc[0])
  print(f"[--------- Percentage Change if Held: {pct_change} ---------]")


  for i in order:
    if i >= max:
      print(f"[------- ⏹️⏹️ {stock} Price rose 10% due to exit orders ⏹️⏹️ -------]")
      return 0.1
    elif i < min:
      print(f"[------- ⏹️⏹️ {stock }Price rose 10% due to exit orders ⏹️⏹️ -------]")
      return -0.1

  print(f'''{stock}
    initial close: {initial_price["Close"]},
    new close: {new_price["Close"]}
    ''')

  print(f"Percentage Change if Held: {pct_change}")
  return pct_change

def backtest2(stock, date, repititions):
  df = pd.DataFrame()
  dictt = {'-3':0, "-2": 1, "-1":2, "1":3, "2" : 4, "3" : 5 }
  verdicts = []
  n3 = [] #negative 3
  n2 = []
  n1 = []
  p1 = []
  p2 = []
  p3 = [] #positive 3
  p = [1,2,3]
  n = [-1,-2,-3]
  dates = []
  results = []
  pct_changes = []

  for i in range(repititions):
    print((i/repititions)*100,' % Done')
    verdict, proba = backtest_technical_model(stock, date)
    verdicts.append(int(verdict))
    n3.append(proba[0][0])
    n2.append(proba[0][1])
    n1.append(proba[0][2])
    p1.append(proba[0][3])
    p2.append(proba[0][4])
    p3.append(proba[0][5])
    dates.append(date)
    date = change_days(date, 1)
    pct_change = backtest(stock, date, "mo")
    pct_changes.append(pct_change)
    if pct_change >0 and verdict in p:
      results.append(1)
    elif pct_change < 0 and verdict in n:
      results.append(1)
    else:
      results.append(0)


  df['date'] = dates
  df["verdicts"] = verdicts
  df["pct_chng"] = pct_changes
  df["results"] = results
  df["n3"] = n3
  df["n2"] = n2
  df["n1"] = n1
  df["p1"] = p1
  df["p2"] = p2
  df["p3"] = p3
  return df

def technical_model(stock, date):
  X,y = data(stock, change_months(date, -48), date)
  vote.fit(X,y.values.ravel())
  pred_df = pred_data(stock, date)
  #print(pred_df)
  pred = vote.predict(pred_df)
  proba = vote.predict_proba(pred_df)
  print(pred, proba)
  if len(proba[0]) == 6:
    print(f"""
    🔹{stock.upper()}🔹{pred}🔹{'🔷Bull🔷' if pred == 3 else '🔷Bear🔷' if pred == -3 else '◽?◽'} 🔹Bull Probability:{proba[0][5]}
          """)
  else:
    print("🔻 Error occured 🔻 Less than 6 labels 🔻")
    return  pred, 0

  try:
    return  pred,proba
  except Exception:
    return  pred, 0

def backtest_technical_model(stock, date):
  X,y = data(stock, change_months(date, -48), date,shuffle = False)

  X = X.iloc[:-22]
  y = y.iloc[:-22]

  X = pd.concat([X,y], axis=1)
  X = X.sample(frac=1, random_state=1)
  y = X.pop("label")

  vote.fit(X,y.values.ravel())
  pred_df = pred_data(stock, date)
  #print(pred_df)
  pred = vote.predict(pred_df)
  proba = vote.predict_proba(pred_df)
  print(pred, proba)
  if len(proba[0]) == 6:
    print(f"""
    🔹{stock.upper()}🔹{pred}🔹{'🔷Bull🔷' if pred == 3 else '🔷Bear🔷' if pred == -3 else '◽?◽'} 🔹Bull Probability:{proba[0][5]}
          """)
  else:
    print("🔻 Error occured 🔻 Less than 6 labels 🔻")
    return  pred, 0

  try:
    return  pred,proba
  except Exception:
    return  pred, 0

def simple_rsi(prices, timeperiod=14):
    # Calculate price changes (delta)
    delta = prices.diff()

    # Separate gains and losses
    gain = delta.where(delta > 0, 0)
    loss = -delta.where(delta < 0, 0)

    # Calculate RS using Simple Moving Average (SMA)
    avg_gain = gain.rolling(window=timeperiod).mean()
    avg_loss = loss.rolling(window=timeperiod).mean()

    rs = avg_gain / avg_loss

    # Apply your formula
    rsi = 100 - (100 / (1 + rs))
    return rsi

In [ ]:
# NOT VERY USEFUL
def DCS(proba): #Directional Confidence Score
  scores = []
  for i in range(len(proba)):
    x = proba[i][0]
    y = proba[i][round((len(proba[0])/2)-0.01)] #get middle class. Round rounds down, but this is find cuz first index is 0 anyways
    z = proba[i][-1]
    score = (z-x)*(1-y)
    scores.append(float(score))
  return scores

#Loading Algorithms

In [ ]:
# FOR MOMENTUM MODEL

#ADA NOT READY
ADA = AdaBoostClassifier(estimator=DecisionTreeClassifier(random_state=0, class_weight='balanced', min_samples_split=15, max_depth=100, max_leaf_nodes=18), random_state=0, learning_rate=0.01)
RF = RandomForestClassifier(random_state = 1,class_weight='balanced')
GB = GradientBoostingClassifier(random_state=0, learning_rate=0.05, )
ET = ExtraTreesClassifier(random_state = 1,class_weight='balanced')
BGRF = BaggingClassifier(estimator = RandomForestClassifier(random_state = 1, class_weight='balanced'), random_state =1)
LGBM = lgb.LGBMClassifier(verbose=-1, random_state=1,class_weight='balanced')
KNN = KNeighborsClassifier(n_neighbors = 11)
SVM = SVC(random_state=1, class_weight='balanced')

vote = VotingClassifier(estimators=[('RF', RF),('GB', GB), ('ET', ET)], voting='soft')

print("✅ Done loading the model ✅")
vote
#vote_score = cross_val_score(vote, X,y,cv=5)

#On SPGI: Cross validation score:
#[0.90106007 0.89399293 0.90106007 0.89399293 0.87588652]

✅ Done loading the model ✅

VotingClassifier(estimators=[('RF',
                              RandomForestClassifier(class_weight='balanced',
                                                     random_state=1)),
                             ('GB',
                              GradientBoostingClassifier(learning_rate=0.05,
                                                         random_state=0)),
                             ('ET',
                              ExtraTreesClassifier(class_weight='balanced',
                                                   random_state=1))],
                 voting='soft')

#ROC Classification

In [ ]:
# ROC DATA
def ROC_data(stock, startdate, enddate, shuffle=True, clean = True, traceback=0, classification_type = 'binary'):
  stock_data = yf.Ticker(stock).history(start = startdate, end=enddate)
  stock_data = stock_data.rename(columns={'Close': 'Close-0d', 'High': 'High-0d', 'Low': 'Low-0d', 'Volume': 'Volume-0d'})

  #Closing prices on previous days:
  for i in range(1, 60):
          stock_data[f"Close-{i}d"] = stock_data["Close-0d"].shift(i)
          stock_data[f"High-{i}d"] = stock_data["High-0d"].shift(i)
          stock_data[f"Low-{i}d"] = stock_data["Low-0d"].shift(i)
          stock_data[f"Volume-{i}d"] = stock_data["Volume-0d"].shift(i)

  # Momentum Indicators
  stock_data["ROC"] = ta.ROC(stock_data["Close-0d"], timeperiod=5)
  stock_data[f"CCI"] = ta.CCI(stock_data[f"High-0d"], stock_data[f"Low-0d"], stock_data[f"Close-0d"], timeperiod=5)
  stock_data['OBV'] = ta.OBV(stock_data['Close-0d'], stock_data['Volume-0d'])
  stock_data['OB-ROC'] = ta.OBV(stock_data['Close-0d'], stock_data['ROC']) # <----- [ =========================== EXPERIMENTAL =========================== ]
  stock_data['stoch-ROC %K'], stock_data['stoch-ROC %D'] = ta.STOCHRSI(stock_data['Close-0d'], timeperiod = 14, fastk_period=2, fastd_period=3, fastd_matype=0) # <----- [ =========================== EXPERIMENTAL =========================== ]
  stock_data['ROC-PPO'] = ta.PPO(stock_data['ROC'], fastperiod=3, slowperiod=5)

  stock_data[f'stochastic oscillator %K'], stock_data[f'stochastic oscillator %D'] = ta.STOCH(
      stock_data[f'High-0d'], stock_data[f'Low-0d'], stock_data[f'Close-0d'],
      fastk_period=2, slowk_period=5, slowk_matype=0, slowd_period=2, slowd_matype=0
  )

  time_periods = [2,3,4,5,6,7]

  for tp in time_periods:
      stock_data[f'OBV_slope(tp={tp})'] = ta.LINEARREG_SLOPE(stock_data['OBV'], timeperiod=tp)
      stock_data[f'ROC_slope(tp={tp})'] = ta.LINEARREG_SLOPE(stock_data['ROC'], timeperiod=tp)
      stock_data[f'CCI_slope(tp={tp})'] = ta.LINEARREG_SLOPE(stock_data['CCI'], timeperiod=tp)
      stock_data[f'stoch_%K_slope(tp={tp})'] = ta.LINEARREG_SLOPE(stock_data['stochastic oscillator %K'], timeperiod=tp)
      stock_data[f'Close_0d_slope(tp={tp})'] = ta.LINEARREG_SLOPE(stock_data['Close-0d'], timeperiod=tp)
      stock_data[f'OB-ROC_slope(tp={tp})'] = ta.LINEARREG_SLOPE(stock_data['OB-ROC'], timeperiod=tp) # <----- [ =========================== EXPERIMENTAL =========================== ]

  for tp in time_periods:
      stock_data[f'OBV_slope(tp={tp})s_slope'] = ta.LINEARREG_SLOPE(stock_data[f'OBV_slope(tp={tp})'], timeperiod=tp)
      stock_data[f'ROC_slope(tp={tp})s_slope'] = ta.LINEARREG_SLOPE(stock_data[f'ROC_slope(tp={tp})'], timeperiod=tp)
      stock_data[f'CCI_slope(tp={tp})s_slope'] = ta.LINEARREG_SLOPE(stock_data[f'CCI_slope(tp={tp})'], timeperiod=tp)
      stock_data[f'stoch_%K_slope(tp={tp})s_slope'] = ta.LINEARREG_SLOPE(stock_data[f'stoch_%K_slope(tp={tp})'], timeperiod=tp)
      stock_data[f'Close_0d_slope(tp={tp})s_slope'] = ta.LINEARREG_SLOPE(stock_data[f'Close_0d_slope(tp={tp})'], timeperiod=tp)
      stock_data[f'OB-ROC_slope(tp={tp})s_slope'] = ta.LINEARREG_SLOPE(stock_data[f'OB-ROC_slope(tp={tp})'], timeperiod=tp)# <----- [ =========================== EXPERIMENTAL =========================== ]

      stock_data[f'OBV_slope(tp={tp})s_ROC'] = ta.ROC(stock_data[f'OBV_slope(tp={tp})'], timeperiod=tp)
      stock_data[f'ROC_slope(tp={tp})s_ROC'] = ta.ROC(stock_data[f'ROC_slope(tp={tp})'], timeperiod=tp)
      stock_data[f'CCI_slope(tp={tp})s_ROC'] = ta.ROC(stock_data[f'CCI_slope(tp={tp})'], timeperiod=tp)
      stock_data[f'stoch_%K_slope(tp={tp})s_ROC'] = ta.ROC(stock_data[f'stoch_%K_slope(tp={tp})'], timeperiod=tp)
      stock_data[f'Close_0d_slope(tp={tp})s_ROC'] = ta.ROC(stock_data[f'Close_0d_slope(tp={tp})'], timeperiod=tp)
      stock_data[f'OB-ROC_slope(tp={tp})s_ROC'] = ta.ROC(stock_data[f'OB-ROC_slope(tp={tp})'], timeperiod=tp)# <----- [ =========================== EXPERIMENTAL =========================== ]


  stock_data["future"] = stock_data['ROC'].shift(traceback)
  stock_data["future_change"] = (stock_data["future"]-stock_data[f"ROC"])

  if classification_type.lower() == 'roc_change':
    stock_data["label"] = np.where(stock_data["future_change"] > 0, 1,0)
  elif classification_type.lower() == 'roc':
    stock_data["label"] = np.where(stock_data['future'] > 0, 1, 0)

  else:
    print('Please Enter A Suitable Classification Type.')
    return 'Please Enter A Suitable Classification Type.', 'Please Enter A Suitable Classification Type.'


  # Replace infinite values with NaN
  stock_data[np.isinf(stock_data)] = np.nan
  # Drop all Nan values
  stock_data = stock_data.dropna()

  stock_data = stock_data.drop(columns=['future', 'future_change'])

  #Drop uncorrelated features
  stock_data = stock_data.drop(columns=[ 'Stock Splits', 'Dividends'])
  #stock_data = stock_data.drop(columns = drpcol)

  for i in range(1, 60):
    stock_data = stock_data.drop(columns=[f"Close-{i}d", f"High-{i}d", f"Low-{i}d", f'Volume-{i}d'])

  if shuffle == True:
    #shuffling the data
    stock_data = stock_data.sample(frac=1, random_state = 1)

  label = pd.DataFrame()
  label["label"] = stock_data.pop("label")

  if clean == True:
    iso = IsolationForest(random_state=0)
    iso.fit(stock_data)
    outliers = iso.predict(stock_data)
    stock_data = stock_data[outliers == 1]
    label = label[outliers==1]

  return stock_data, label

In [ ]:
clfs = [RF, LGBM, GB, ADA, vote, vote, ET, KNN, vote]

In [ ]:
stocks = ['aapl', 'wmt', 'pltr', 'ko']
performances = {}

for clf in clfs:

  accuracies = []

  for stock in stocks:
    date = "2026-01-01"
    pred = 'ROC'.upper()
    traceback = -5
    classification_type = 'roc_change'

    X,y = ROC_data(stock, change_months(date, -100), date, shuffle = False, traceback = traceback, classification_type= classification_type)

    print(X.shape, y.shape)

    X_test = X.iloc[-200:]
    y_test = y.iloc[-200:]

    X = X.iloc[:-205]
    y = y.iloc[:-205]

    X = pd.concat([X,y], axis=1)
    X_train = X.sample(frac=1, random_state=1)

    y_train = X_train.pop("label")

    print(X_train.shape, y_train.shape, X_test.shape, y_test.shape)

    clf.fit(X_train, y_train.values.ravel())
    y_pred = clf.predict(X_test)
    y_pred_proba = clf.predict_proba(X_test)

    print(f"{stock} Accuracy: ",clf.score(X_test, y_test))
    cm = confusion_matrix(y_test, y_pred)
    cf = classification_report(y_test, y_pred)
    print(cm,'\n',cf)

    accuracies.append(precision_score(y_test, y_pred, average='macro'))

  performances[str(clf)] = sum(accuracies)/len(accuracies)
  print(performances)

(2018, 122) (2018, 1)
(1813, 122) (1813,) (200, 122) (200, 1)
aapl Accuracy:  0.725
[[81 25]
 [30 64]]
               precision    recall  f1-score   support

           0       0.73      0.76      0.75       106
           1       0.72      0.68      0.70        94

    accuracy                           0.72       200
   macro avg       0.72      0.72      0.72       200
weighted avg       0.72      0.72      0.72       200

(2006, 122) (2006, 1)
(1801, 122) (1801,) (200, 122) (200, 1)
wmt Accuracy:  0.74
[[73 25]
 [27 75]]
               precision    recall  f1-score   support

           0       0.73      0.74      0.74        98
           1       0.75      0.74      0.74       102

    accuracy                           0.74       200
   macro avg       0.74      0.74      0.74       200
weighted avg       0.74      0.74      0.74       200

(1244, 122) (1244, 1)
(1039, 122) (1039,) (200, 122) (200, 1)
pltr Accuracy:  0.66
[[81 19]
 [49 51]]
               precision    recall  f1-score   support

           0       0.62      0.81      0.70       100
           1       0.73      0.51      0.60       100

    accuracy                           0.66       200
   macro avg       0.68      0.66      0.65       200
weighted avg       0.68      0.66      0.65       200

(2001, 122) (2001, 1)
(1796, 122) (1796,) (200, 122) (200, 1)
ko Accuracy:  0.78
[[74 18]
 [26 82]]
               precision    recall  f1-score   support

           0       0.74      0.80      0.77        92
           1       0.82      0.76      0.79       108

    accuracy                           0.78       200
   macro avg       0.78      0.78      0.78       200
weighted avg       0.78      0.78      0.78       200

{"RandomForestClassifier(class_weight='balanced', random_state=1)": 0.7300599006216983}
(2018, 122) (2018, 1)
(1813, 122) (1813,) (200, 122) (200, 1)
aapl Accuracy:  0.68
[[75 31]
 [33 61]]
               precision    recall  f1-score   support

           0       0.69      0.71      0.70       106
           1       0.66      0.65      0.66        94

    accuracy                           0.68       200
   macro avg       0.68      0.68      0.68       200
weighted avg       0.68      0.68      0.68       200

(2006, 122) (2006, 1)
(1801, 122) (1801,) (200, 122) (200, 1)
wmt Accuracy:  0.73
[[67 31]
 [23 79]]
               precision    recall  f1-score   support

           0       0.74      0.68      0.71        98
           1       0.72      0.77      0.75       102

    accuracy                           0.73       200
   macro avg       0.73      0.73      0.73       200
weighted avg       0.73      0.73      0.73       200

(1244, 122) (1244, 1)
(1039, 122) (1039,) (200, 122) (200, 1)
pltr Accuracy:  0.695
[[70 30]
 [31 69]]
               precision    recall  f1-score   support

           0       0.69      0.70      0.70       100
           1       0.70      0.69      0.69       100

    accuracy                           0.69       200
   macro avg       0.70      0.69      0.69       200
weighted avg       0.70      0.69      0.69       200

(2001, 122) (2001, 1)
(1796, 122) (1796,) (200, 122) (200, 1)
ko Accuracy:  0.79
[[74 18]
 [24 84]]
               precision    recall  f1-score   support

           0       0.76      0.80      0.78        92
           1       0.82      0.78      0.80       108

    accuracy                           0.79       200
   macro avg       0.79      0.79      0.79       200
weighted avg       0.79      0.79      0.79       200

{"RandomForestClassifier(class_weight='balanced', random_state=1)": 0.7300599006216983, "LGBMClassifier(class_weight='balanced', random_state=1, verbose=-1)": 0.7235980802266249}
(2018, 122) (2018, 1)
(1813, 122) (1813,) (200, 122) (200, 1)
aapl Accuracy:  0.745
[[88 18]
 [33 61]]
               precision    recall  f1-score   support

           0       0.73      0.83      0.78       106
           1       0.77      0.65      0.71        94

    accuracy                           0.74       200
   macro avg       0.75      0.74      0.74       200
weighted avg       0.75      0.74      0.74       200

(2006, 122) (2006, 1)
(1801, 122) (1801,) (200, 122) (200, 1)
wmt Accuracy:  0.72
[[70 28]
 [28 74]]
               precision    recall  f1-score   support

           0       0.71      0.71      0.71        98
           1       0.73      0.73      0.73       102

    accuracy                           0.72       200
   macro avg       0.72      0.72      0.72       200
weighted avg       0.72      0.72      0.72       200

(1244, 122) (1244, 1)
(1039, 122) (1039,) (200, 122) (200, 1)
pltr Accuracy:  0.62
[[77 23]
 [53 47]]
               precision    recall  f1-score   support

           0       0.59      0.77      0.67       100
           1       0.67      0.47      0.55       100

    accuracy                           0.62       200
   macro avg       0.63      0.62      0.61       200
weighted avg       0.63      0.62      0.61       200

(2001, 122) (2001, 1)
(1796, 122) (1796,) (200, 122) (200, 1)
ko Accuracy:  0.8
[[73 19]
 [21 87]]
               precision    recall  f1-score   support

           0       0.78      0.79      0.78        92
           1       0.82      0.81      0.81       108

    accuracy                           0.80       200
   macro avg       0.80      0.80      0.80       200
weighted avg       0.80      0.80      0.80       200

{"RandomForestClassifier(class_weight='balanced', random_state=1)": 0.7300599006216983, "LGBMClassifier(class_weight='balanced', random_state=1, verbose=-1)": 0.7235980802266249, 'GradientBoostingClassifier(learning_rate=0.05, random_state=0)': 0.7250359077211621}
(2018, 122) (2018, 1)
(1813, 122) (1813,) (200, 122) (200, 1)
aapl Accuracy:  0.785
[[81 25]
 [18 76]]
               precision    recall  f1-score   support

           0       0.82      0.76      0.79       106
           1       0.75      0.81      0.78        94

    accuracy                           0.79       200
   macro avg       0.79      0.79      0.78       200
weighted avg       0.79      0.79      0.79       200

(2006, 122) (2006, 1)
(1801, 122) (1801,) (200, 122) (200, 1)
wmt Accuracy:  0.745
[[70 28]
 [23 79]]
               precision    recall  f1-score   support

           0       0.75      0.71      0.73        98
           1       0.74      0.77      0.76       102

    accuracy                           0.74       200
   macro avg       0.75      0.74      0.74       200
weighted avg       0.75      0.74      0.74       200

(1244, 122) (1244, 1)
(1039, 122) (1039,) (200, 122) (200, 1)
pltr Accuracy:  0.58
[[68 32]
 [52 48]]
               precision    recall  f1-score   support

           0       0.57      0.68      0.62       100
           1       0.60      0.48      0.53       100

    accuracy                           0.58       200
   macro avg       0.58      0.58      0.58       200
weighted avg       0.58      0.58      0.58       200

(2001, 122) (2001, 1)
(1796, 122) (1796,) (200, 122) (200, 1)
ko Accuracy:  0.775
[[67 25]
 [20 88]]
               precision    recall  f1-score   support

           0       0.77      0.73      0.75        92
           1       0.78      0.81      0.80       108

    accuracy                           0.78       200
   macro avg       0.77      0.77      0.77       200
weighted avg       0.77      0.78      0.77       200

{"RandomForestClassifier(class_weight='balanced', random_state=1)": 0.7300599006216983, "LGBMClassifier(class_weight='balanced', random_state=1, verbose=-1)": 0.7235980802266249, 'GradientBoostingClassifier(learning_rate=0.05, random_state=0)': 0.7250359077211621, "AdaBoostClassifier(estimator=DecisionTreeClassifier(class_weight='balanced',\n                                                    max_depth=100,\n                                                    max_leaf_nodes=18,\n                                                    min_samples_split=15,\n                                                    random_state=0),\n                   learning_rate=0.01, random_state=0)": 0.7221507082376539}
(2018, 122) (2018, 1)
(1813, 122) (1813,) (200, 122) (200, 1)
aapl Accuracy:  0.715
[[81 25]
 [32 62]]
               precision    recall  f1-score   support

           0       0.72      0.76      0.74       106
           1       0.71      0.66      0.69        94

    accuracy                           0.71       200
   macro avg       0.71      0.71      0.71       200
weighted avg       0.71      0.71      0.71       200

(2006, 122) (2006, 1)
(1801, 122) (1801,) (200, 122) (200, 1)
wmt Accuracy:  0.735
[[72 26]
 [27 75]]
               precision    recall  f1-score   support

           0       0.73      0.73      0.73        98
           1       0.74      0.74      0.74       102

    accuracy                           0.73       200
   macro avg       0.73      0.73      0.73       200
weighted avg       0.74      0.73      0.74       200

(1244, 122) (1244, 1)
(1039, 122) (1039,) (200, 122) (200, 1)
pltr Accuracy:  0.66
[[79 21]
 [47 53]]
               precision    recall  f1-score   support

           0       0.63      0.79      0.70       100
           1       0.72      0.53      0.61       100

    accuracy                           0.66       200
   macro avg       0.67      0.66      0.65       200
weighted avg       0.67      0.66      0.65       200

(2001, 122) (2001, 1)
(1796, 122) (1796,) (200, 122) (200, 1)
ko Accuracy:  0.775
[[72 20]
 [25 83]]
               precision    recall  f1-score   support

           0       0.74      0.78      0.76        92
           1       0.81      0.77      0.79       108

    accuracy                           0.78       200
   macro avg       0.77      0.78      0.77       200
weighted avg       0.78      0.78      0.78       200

{"RandomForestClassifier(class_weight='balanced', random_state=1)": 0.7300599006216983, "LGBMClassifier(class_weight='balanced', random_state=1, verbose=-1)": 0.7235980802266249, 'GradientBoostingClassifier(learning_rate=0.05, random_state=0)': 0.7250359077211621, "AdaBoostClassifier(estimator=DecisionTreeClassifier(class_weight='balanced',\n                                                    max_depth=100,\n                                                    max_leaf_nodes=18,\n                                                    min_samples_split=15,\n                                                    random_state=0),\n                   learning_rate=0.01, random_state=0)": 0.7221507082376539, "VotingClassifier(estimators=[('RF',\n                              RandomForestClassifier(class_weight='balanced',\n                                                     random_state=1)),\n                             ('GB',\n                              GradientBoostingClassifier(learning_rate=0.05,\n                                                         random_state=0)),\n                             ('ET',\n                              ExtraTreesClassifier(class_weight='balanced',\n                                                   random_state=1))],\n                 voting='soft')": 0.723824806163416}
(2018, 122) (2018, 1)
(1813, 122) (1813,) (200, 122) (200, 1)
aapl Accuracy:  0.715
[[81 25]
 [32 62]]
               precision    recall  f1-score   support

           0       0.72      0.76      0.74       106
           1       0.71      0.66      0.69        94

    accuracy                           0.71       200
   macro avg       0.71      0.71      0.71       200
weighted avg       0.71      0.71      0.71       200

(2006, 122) (2006, 1)
(1801, 122) (1801,) (200, 122) (200, 1)
wmt Accuracy:  0.735
[[72 26]
 [27 75]]
               precision    recall  f1-score   support

           0       0.73      0.73      0.73        98
           1       0.74      0.74      0.74       102

    accuracy                           0.73       200
   macro avg       0.73      0.73      0.73       200
weighted avg       0.74      0.73      0.74       200

(1244, 122) (1244, 1)
(1039, 122) (1039,) (200, 122) (200, 1)
pltr Accuracy:  0.66
[[79 21]
 [47 53]]
               precision    recall  f1-score   support

           0       0.63      0.79      0.70       100
           1       0.72      0.53      0.61       100

    accuracy                           0.66       200
   macro avg       0.67      0.66      0.65       200
weighted avg       0.67      0.66      0.65       200

(2001, 122) (2001, 1)
(1796, 122) (1796,) (200, 122) (200, 1)
ko Accuracy:  0.775
[[72 20]
 [25 83]]
               precision    recall  f1-score   support

           0       0.74      0.78      0.76        92
           1       0.81      0.77      0.79       108

    accuracy                           0.78       200
   macro avg       0.77      0.78      0.77       200
weighted avg       0.78      0.78      0.78       200

{"RandomForestClassifier(class_weight='balanced', random_state=1)": 0.7300599006216983, "LGBMClassifier(class_weight='balanced', random_state=1, verbose=-1)": 0.7235980802266249, 'GradientBoostingClassifier(learning_rate=0.05, random_state=0)': 0.7250359077211621, "AdaBoostClassifier(estimator=DecisionTreeClassifier(class_weight='balanced',\n                                                    max_depth=100,\n                                                    max_leaf_nodes=18,\n                                                    min_samples_split=15,\n                                                    random_state=0),\n                   learning_rate=0.01, random_state=0)": 0.7221507082376539, "VotingClassifier(estimators=[('RF',\n                              RandomForestClassifier(class_weight='balanced',\n                                                     random_state=1)),\n                             ('GB',\n                              GradientBoostingClassifier(learning_rate=0.05,\n                                                         random_state=0)),\n                             ('ET',\n                              ExtraTreesClassifier(class_weight='balanced',\n                                                   random_state=1))],\n                 voting='soft')": 0.723824806163416}
(2018, 122) (2018, 1)
(1813, 122) (1813,) (200, 122) (200, 1)
aapl Accuracy:  0.725
[[83 23]
 [32 62]]
               precision    recall  f1-score   support

           0       0.72      0.78      0.75       106
           1       0.73      0.66      0.69        94

    accuracy                           0.72       200
   macro avg       0.73      0.72      0.72       200
weighted avg       0.73      0.72      0.72       200

(2006, 122) (2006, 1)
(1801, 122) (1801,) (200, 122) (200, 1)
wmt Accuracy:  0.725
[[71 27]
 [28 74]]
               precision    recall  f1-score   support

           0       0.72      0.72      0.72        98
           1       0.73      0.73      0.73       102

    accuracy                           0.72       200
   macro avg       0.72      0.72      0.72       200
weighted avg       0.73      0.72      0.73       200

(1244, 122) (1244, 1)
(1039, 122) (1039,) (200, 122) (200, 1)
pltr Accuracy:  0.675
[[84 16]
 [49 51]]
               precision    recall  f1-score   support

           0       0.63      0.84      0.72       100
           1       0.76      0.51      0.61       100

    accuracy                           0.68       200
   macro avg       0.70      0.68      0.67       200
weighted avg       0.70      0.68      0.67       200

(2001, 122) (2001, 1)
(1796, 122) (1796,) (200, 122) (200, 1)
ko Accuracy:  0.75
[[70 22]
 [28 80]]
               precision    recall  f1-score   support

           0       0.71      0.76      0.74        92
           1       0.78      0.74      0.76       108

    accuracy                           0.75       200
   macro avg       0.75      0.75      0.75       200
weighted avg       0.75      0.75      0.75       200

{"RandomForestClassifier(class_weight='balanced', random_state=1)": 0.7300599006216983, "LGBMClassifier(class_weight='balanced', random_state=1, verbose=-1)": 0.7235980802266249, 'GradientBoostingClassifier(learning_rate=0.05, random_state=0)': 0.7250359077211621, "AdaBoostClassifier(estimator=DecisionTreeClassifier(class_weight='balanced',\n                                                    max_depth=100,\n                                                    max_leaf_nodes=18,\n                                                    min_samples_split=15,\n                                                    random_state=0),\n                   learning_rate=0.01, random_state=0)": 0.7221507082376539, "VotingClassifier(estimators=[('RF',\n                              RandomForestClassifier(class_weight='balanced',\n                                                     random_state=1)),\n                             ('GB',\n                              GradientBoostingClassifier(learning_rate=0.05,\n                                                         random_state=0)),\n                             ('ET',\n                              ExtraTreesClassifier(class_weight='balanced',\n                                                   random_state=1))],\n                 voting='soft')": 0.723824806163416, "ExtraTreesClassifier(class_weight='balanced', random_state=1)": 0.7240460370792741}
(2018, 122) (2018, 1)
(1813, 122) (1813,) (200, 122) (200, 1)
aapl Accuracy:  0.615
[[91 15]
 [62 32]]
               precision    recall  f1-score   support

           0       0.59      0.86      0.70       106
           1       0.68      0.34      0.45        94

    accuracy                           0.61       200
   macro avg       0.64      0.60      0.58       200
weighted avg       0.64      0.61      0.59       200

(2006, 122) (2006, 1)
(1801, 122) (1801,) (200, 122) (200, 1)
wmt Accuracy:  0.555
[[94  4]
 [85 17]]
               precision    recall  f1-score   support

           0       0.53      0.96      0.68        98
           1       0.81      0.17      0.28       102

    accuracy                           0.56       200
   macro avg       0.67      0.56      0.48       200
weighted avg       0.67      0.56      0.47       200

(1244, 122) (1244, 1)
(1039, 122) (1039,) (200, 122) (200, 1)
pltr Accuracy:  0.515
[[99  1]
 [96  4]]
               precision    recall  f1-score   support

           0       0.51      0.99      0.67       100
           1       0.80      0.04      0.08       100

    accuracy                           0.52       200
   macro avg       0.65      0.52      0.37       200
weighted avg       0.65      0.52      0.37       200

(2001, 122) (2001, 1)
(1796, 122) (1796,) (200, 122) (200, 1)
ko Accuracy:  0.57
[[74 18]
 [68 40]]
               precision    recall  f1-score   support

           0       0.52      0.80      0.63        92
           1       0.69      0.37      0.48       108

    accuracy                           0.57       200
   macro avg       0.61      0.59      0.56       200
weighted avg       0.61      0.57      0.55       200


In [ ]:
df = pd.DataFrame()
df['Change'] = X_test['Close-0d'].shift(-5) - X_test['Close-0d']
df['ROC'] = X_test['ROC']
df['ROC_label'] = y_test
df['ROC_pred'] = y_pred
df['ROC_proba'] = [x[1] for x in y_pred_proba]
df['Price_label'] = np.where(df['Change'] > 0, 1, 0)
df['Price_pred'] = np.where((df['ROC_proba'] > 0.5) & (X_test['ROC']>-2), 1,
                            np.where(((1-df['ROC_proba']) > 0.5) & (X_test['ROC']<2), 0, 9))
df = df.dropna()
print(df.to_string())

                              Change        ROC  ROC_label  ROC_pred  ROC_proba  Price_label  Price_pred
Date
2025-03-10 00:00:00-04:00   5.488861  -3.780474          1         1   0.820232            1           9
2025-03-11 00:00:00-04:00   3.318848   1.151787          1         0   0.366749            1           0
2025-03-12 00:00:00-04:00   2.916245   1.781734          1         0   0.231557            1           0
2025-03-13 00:00:00-04:00   5.076447  -0.571661          1         1   0.623362            1           1
2025-03-14 00:00:00-04:00  -0.049103   2.809306          0         0   0.268017            0           9
2025-03-17 00:00:00-04:00  -0.058929   3.786757          0         0   0.129969            0           9
2025-03-18 00:00:00-04:00   2.533310   2.290910          0         0   0.250326            1           9
2025-03-19 00:00:00-04:00  -0.520432   1.976827          0         0   0.244233            0           0
2025-03-20 00:00:00-04:00  -2.778793   3.538669          0         0   0.149021            0           9
2025-03-21 00:00:00-04:00  -5.420135  -0.033248          0         1   0.551098            0           1
2025-03-24 00:00:00-04:00  -6.176163  -0.039172          0         1   0.612371            0           1
2025-03-25 00:00:00-04:00  -5.724487   1.709511          0         0   0.299299            0           0
2025-03-26 00:00:00-04:00  -4.830963  -0.345945          0         0   0.469901            0           0
2025-03-27 00:00:00-04:00  -8.542572  -1.870828          0         1   0.775680            0           1
2025-03-28 00:00:00-04:00 -17.605553  -3.671201          0         1   0.887441            0           9
2025-03-31 00:00:00-04:00 -17.978691  -4.107071          0         1   0.866322            0           9
2025-04-01 00:00:00-04:00 -20.138893  -3.798032          0         1   0.786785            0           9
2025-04-02 00:00:00-04:00  -9.269165  -3.222419          0         1   0.601507            0           9
2025-04-03 00:00:00-04:00  -6.647522  -5.860951          1         1   0.746348            0           9
2025-04-04 00:00:00-04:00   8.876442 -12.379172          1         1   0.866952            1           9
2025-04-07 00:00:00-04:00   7.325020 -12.467659          1         1   0.820727            1           9
2025-04-08 00:00:00-04:00   7.953423 -13.889086          1         1   0.905729            1           9
2025-04-09 00:00:00-04:00  -7.717789  -6.388724          1         1   0.617147            0           9
2025-04-10 00:00:00-04:00  -2.710045  -4.844728          1         0   0.488899            0           0
2025-04-11 00:00:00-04:00  -9.681595   7.123173          0         0   0.216942            0           9
2025-04-14 00:00:00-04:00   0.314209   5.803194          0         0   0.274313            1           9
2025-04-15 00:00:00-04:00   0.785538   6.369919          0         0   0.265630            1           9
2025-04-16 00:00:00-04:00   8.267639  -5.682484          1         1   0.747671            1           9
2025-04-17 00:00:00-04:00   6.981346  -2.075646          1         1   0.833674            1           9
2025-04-21 00:00:00-04:00  11.625748  -7.252672          1         1   0.909545            1           9
2025-04-22 00:00:00-04:00   2.012894   0.235276          1         0   0.451252            1           0
2025-04-23 00:00:00-04:00   2.798431   0.591464          1         0   0.456869            1           0
2025-04-24 00:00:00-04:00  -0.962265   6.454083          0         0   0.255127            0           9
2025-04-25 00:00:00-04:00   4.673874   5.460410          0         0   0.153930            1           9
2025-04-28 00:00:00-04:00   2.818069   9.390109          0         0   0.218699            1           9
2025-04-29 00:00:00-04:00  -0.353485   1.503695          0         0   0.383418            0           0
2025-04-30 00:00:00-04:00  -0.265121   2.094665          0         0   0.450692            0           9
2025-05-01 00:00:00-04:00   3.161728  -0.705644          1         1   0.641107            1           1
2025-05-02 00:00:00-04:00   0.510605   3.466359          0         0   0.207380            1           9
2025-05-05 00:00:00-04:00   9.357574   2.080767          1         0   0.277402            1           9
2025-05-06 00:00:00-04:00  12.489853  -0.260153          1         1   0.599090            1           1
2025-05-07 00:00:00-04:00   9.072815  -0.194376          1         1   0.596094            1           1
2025-05-08 00:00:00-04:00   7.482147   2.335020          1         0   0.307640            1           9
2025-05-09 00:00:00-04:00  10.319794   0.366001          1         0   0.313951            1           0
2025-05-12 00:00:00-04:00   3.741043   6.768479          0         0   0.084076            1           9
2025-05-13 00:00:00-04:00   3.348282   9.216069          0         0   0.080943            1           9
2025-05-14 00:00:00-04:00   1.492477   6.664751          0         0   0.186868            1           9
2025-05-15 00:00:00-04:00   1.021179   5.399681          0         0   0.215035            1           9
2025-05-16 00:00:00-04:00  -4.680740   7.370243          0         0   0.251613            0           9
2025-05-19 00:00:00-04:00  -3.846939   2.534413          0         0   0.283385            0           9
2025-05-20 00:00:00-04:00  -4.675735   2.262163          0         0   0.255507            0           9
2025-05-21 00:00:00-04:00   0.945435   1.027848          0         0   0.396196            1           0
2025-05-22 00:00:00-04:00  -0.690704   0.699205          0         0   0.465603            0           0
2025-05-23 00:00:00-04:00  -1.203796  -3.113447          1         1   0.806957            0           9
2025-05-27 00:00:00-04:00  -1.341934  -2.541736          1         1   0.786410            0           9
2025-05-28 00:00:00-04:00  -1.825424  -3.089134          1         1   0.767704            0           9
2025-05-29 00:00:00-04:00  -3.325241   0.644483          0         0   0.311714            0           0
2025-05-30 00:00:00-04:00  -2.812149  -0.469644          0         1   0.635671            0           1
2025-06-02 00:00:00-04:00  -2.141174  -0.826450          0         1   0.721031            0           1
2025-06-03 00:00:00-04:00  -3.029236  -0.909762          0         1   0.692020            0           1
2025-06-04 00:00:00-04:00   0.365067  -1.244452          1         1   0.741086            1           1
2025-06-05 00:00:00-04:00  -1.470200  -2.252231          1         1   0.794402            0           9
2025-06-06 00:00:00-04:00  -3.137741  -1.921141          0         1   0.767920            0           1
2025-06-09 00:00:00-04:00   0.828857  -1.482243          1         1   0.752396            1           1
2025-06-10 00:00:00-04:00  -2.812103  -2.072519          1         1   0.809706            0           9
2025-06-11 00:00:00-04:00  -4.607956   0.252014          0         0   0.416131            0           0
2025-06-12 00:00:00-04:00  -0.730164  -1.018730          1         1   0.566098            0           1
2025-06-13 00:00:00-04:00   5.209839  -2.185560          1         1   0.740910            1           9
2025-06-16 00:00:00-04:00   4.736237   0.582415          1         0   0.403800            1           0
2025-06-17 00:00:00-04:00   5.466385  -1.964682          1         1   0.786742            1           1
2025-06-18 00:00:00-04:00   8.140396  -3.172986          1         1   0.815157            1           9
2025-06-20 00:00:00-04:00   7.883850  -0.511152          1         0   0.452135            1           0
2025-06-23 00:00:00-04:00   4.578354   3.709940          0         0   0.186133            1           9
2025-06-24 00:00:00-04:00   3.887634   3.308753          0         0   0.058505            1           9
2025-06-25 00:00:00-04:00   6.137360   3.895638          1         0   0.157953            1           9
2025-06-26 00:00:00-04:00   2.151047   5.789070          0         0   0.141078            1           9
2025-06-27 00:00:00-04:00  -0.177612   5.547457          0         0   0.154432            0           9
2025-06-30 00:00:00-04:00   1.480087   3.143631          0         0   0.219063            1           9
2025-07-01 00:00:00-04:00   2.141174   2.628931          0         0   0.186365            1           9
2025-07-02 00:00:00-04:00   3.305511   4.209811          0         0   0.106272            1           9
2025-07-03 00:00:00-04:00   2.861465   1.446013          1         0   0.359608            1           0
2025-07-07 00:00:00-04:00   5.989365  -0.118408          1         1   0.649639            1           1
2025-07-08 00:00:00-04:00   2.812119   0.985297          1         0   0.444636            1           0
2025-07-09 00:00:00-04:00   1.559006   1.410834          0         0   0.240815            1           0
2025-07-10 00:00:00-04:00   1.697128   2.175761          0         0   0.210396            1           9
2025-07-11 00:00:00-04:00  -2.575317   1.896164          0         0   0.318263            0           0
2025-07-14 00:00:00-04:00  -5.022369   3.997635          0         0   0.123271            0           9
2025-07-15 00:00:00-04:00  -5.318375   1.853767          0         0   0.274659            0           0
2025-07-16 00:00:00-04:00  -6.650436   1.012949          0         0   0.410113            0           0
2025-07-17 00:00:00-04:00  -9.610580   1.093300          0         0   0.367244            0           0
2025-07-18 00:00:00-04:00  -1.933960  -1.674790          1         1   0.631815            0           1
2025-07-21 00:00:00-04:00  -0.759796  -3.223351          1         1   0.682870            0           9
2025-07-22 00:00:00-04:00   0.582153  -3.442100          1         1   0.732792            1           9
2025-07-23 00:00:00-04:00  -4.144211  -4.277724          1         1   0.815403            0           9
2025-07-24 00:00:00-04:00  -0.078949  -6.124235          1         1   0.896808            0           9
2025-07-25 00:00:00-04:00  -6.768860  -1.279123          0         1   0.694633            0           1
2025-07-28 00:00:00-04:00  -4.124466  -0.503878          0         0   0.479517            0           0
2025-07-29 00:00:00-04:00  -1.677414   0.390206          0         0   0.463174            0           0
2025-07-30 00:00:00-04:00   4.144211  -2.784783          1         1   0.738202            1           9
2025-07-31 00:00:00-04:00   2.486526  -0.053591          1         1   0.603975            1           1
2025-08-01 00:00:00-04:00   8.771881  -4.534937          1         1   0.914313            1           9
2025-08-04 00:00:00-04:00   7.341156  -2.749096          1         1   0.798283            1           9
2025-08-05 00:00:00-04:00   7.656906  -1.119968          1         1   0.512325            1           1
2025-08-06 00:00:00-04:00   9.255356   2.864555          1         0   0.145848            1           9
2025-08-07 00:00:00-04:00   4.844757   1.688786          1         0   0.131609            1           0
2025-08-08 00:00:00-04:00  -0.897919   6.156077          0         0   0.073623            0           9
2025-08-11 00:00:00-04:00  -2.417450   5.031448          0         0   0.114693            0           9
2025-08-12 00:00:00-04:00  -3.463379   5.170233          0         0   0.116483            0           9
2025-08-13 00:00:00-04:00  -5.377579   6.219317          0         0   0.124153            0           9
2025-08-14 00:00:00-04:00  -2.239838   3.235791          0         0   0.259328            0           9
2025-08-15 00:00:00-04:00   6.245926  -0.593613          1         1   0.642893            1           1
2025-08-18 00:00:00-04:00   3.660843  -1.577490          1         1   0.577410            1           1
2025-08-19 00:00:00-04:00   2.914215  -2.223637          1         1   0.691167            1           9
2025-08-20 00:00:00-04:00   2.469986  -3.401989          1         1   0.653450            1           9
2025-08-21 00:00:00-04:00   3.856079  -1.449088          1         0   0.498732            1           0
2025-08-22 00:00:00-04:00  -2.438538   4.153832          0         0   0.125514            0           9
2025-08-25 00:00:00-04:00  -1.566223   2.427146          0         0   0.273798            0           9
2025-08-26 00:00:00-04:00  -4.530136   1.913602          0         0   0.427441            0           0
2025-08-27 00:00:00-04:00  -1.001175   1.617605          0         0   0.358203            0           0
2025-08-28 00:00:00-04:00  -2.240265   2.531416          0         0   0.275133            0           9
2025-08-29 00:00:00-04:00  -1.516647  -1.557064          1         1   0.628888            0           1
2025-09-02 00:00:00-04:00  -1.179611  -1.013802          1         1   0.697534            0           1
2025-09-03 00:00:00-04:00   1.556305  -2.918832          1         1   0.713444            1           9
2025-09-04 00:00:00-04:00   3.915527  -0.645236          1         1   0.658598            1           1
2025-09-05 00:00:00-04:00   2.547577  -1.434366          1         1   0.568711            1           1
2025-09-08 00:00:00-04:00   2.636780  -0.983732          1         1   0.608874            1           1
2025-09-09 00:00:00-04:00   3.390152  -0.771372          1         1   0.637261            1           1
2025-09-10 00:00:00-04:00   1.576126   1.032898          1         0   0.486001            1           0
2025-09-11 00:00:00-04:00  -4.034485   2.539864          0         0   0.287623            0           9
2025-09-12 00:00:00-04:00  -1.258911   1.654864          0         0   0.289274            0           0
2025-09-15 00:00:00-04:00  -2.775558   1.727268          0         0   0.291428            0           0
2025-09-16 00:00:00-04:00  -0.208176   2.234124          0         0   0.259704            0           9
2025-09-17 00:00:00-04:00  -0.555115   1.035359          0         0   0.421109            0           0
2025-09-18 00:00:00-04:00  -2.349304  -2.552205          1         1   0.636370            0           9
2025-09-19 00:00:00-04:00  -3.756943  -0.804455          0         1   0.578175            0           1
2025-09-22 00:00:00-04:00   0.218063  -1.787305          1         1   0.601506            1           1
2025-09-23 00:00:00-04:00  -1.100311  -0.134191          0         1   0.542187            0           1
2025-09-24 00:00:00-04:00   1.387787  -0.360919          1         0   0.480852            1           0
2025-09-25 00:00:00-04:00   5.719650  -1.525087          1         1   0.631521            1           1
2025-09-26 00:00:00-04:00   5.798950  -2.420189          1         1   0.659666            1           9
2025-09-29 00:00:00-04:00   1.833847   0.142976          1         1   0.541748            1           1
2025-09-30 00:00:00-04:00   0.148697  -0.710217          1         1   0.541969            1           1
2025-10-01 00:00:00-04:00   0.000000   0.905565          0         0   0.346974            0           0
2025-10-02 00:00:00-04:00  -5.868347   3.770504          0         0   0.174543            0           9
2025-10-03 00:00:00-04:00  -9.823517   3.828284          0         0   0.161441            0           9
2025-10-06 00:00:00-04:00  -4.787827   1.200669          0         0   0.381303            0           0
2025-10-07 00:00:00-04:00  -2.775574   0.096666          0         1   0.511686            0           1
2025-10-08 00:00:00-04:00  -2.507935   0.000000          0         0   0.427284            0           0
2025-10-09 00:00:00-04:00  -1.457169  -3.727964          1         1   0.655538            0           9
2025-10-10 00:00:00-04:00   3.856049  -6.246059          1         1   0.851251            1           9
2025-10-13 00:00:00-04:00   3.647873  -3.097528          1         1   0.667290            1           9
2025-10-14 00:00:00-04:00  13.986862  -1.802619          1         1   0.606645            1           1
2025-10-15 00:00:00-04:00  13.639923  -1.621803          1         1   0.503708            1           1
2025-10-16 00:00:00-04:00  16.940857  -0.961536          1         1   0.608487            1           1
2025-10-17 00:00:00-04:00  15.622467   2.615122          1         0   0.278922            1           9
2025-10-20 00:00:00-04:00  11.944855   2.435464          1         0   0.236116            1           9
2025-10-21 00:00:00-04:00  -1.992447   9.250635          0         0   0.118160            0           9
2025-10-22 00:00:00-04:00  -0.773178   8.965922          0         0   0.196462            0           9
2025-10-24 00:00:00-04:00  -1.982544  10.390465          0         0   0.148775            0           9
2025-10-27 00:00:00-04:00  -6.155807   8.799586          0         0   0.204858            0           9
2025-10-28 00:00:00-04:00  -6.185547   0.114026          0         1   0.506559            0           1
2025-10-29 00:00:00-04:00  -0.307297  -1.554739          1         1   0.580829            0           1
2025-10-30 00:00:00-04:00  -2.577301  -3.001164          1         1   0.670994            0           9
2025-10-31 00:00:00-04:00  -1.645523  -1.186942          1         1   0.579206            0           1
2025-11-03 00:00:00-05:00   5.432190  -3.687648          1         1   0.617015            1           9
2025-11-04 00:00:00-05:00   8.009476  -3.740335          1         1   0.740363            1           9
2025-11-05 00:00:00-05:00   6.701004  -0.188302          1         1   0.582776            1           1
2025-11-06 00:00:00-05:00   6.710892  -1.562024          1         1   0.632172            1           1
2025-11-07 00:00:00-05:00   3.429886  -0.997002          1         1   0.618023            1           1
2025-11-10 00:00:00-05:00  -1.555649   3.378760          0         0   0.185818            0           9
2025-11-11 00:00:00-05:00  -2.148697   5.031438          0         0   0.095400            0           9
2025-11-12 00:00:00-05:00  -3.751190   4.113921          0         0   0.119215            0           9
2025-11-13 00:00:00-05:00  -5.256393   4.131809          0         0   0.155607            0           9
2025-11-14 00:00:00-05:00   0.507721   2.099054          0         0   0.366094            1           9
2025-11-17 00:00:00-05:00   4.151382  -0.935972          1         1   0.671057            1           1
2025-11-18 00:00:00-05:00   5.724319  -1.285120          1         1   0.582786            1           1
2025-11-19 00:00:00-05:00   4.201157  -2.211955          1         1   0.665618            1           9
2025-11-20 00:00:00-05:00   7.406769  -3.107882          1         1   0.682032            1           9
2025-11-21 00:00:00-05:00   2.379318   0.304332          1         0   0.367002            1           0
2025-11-24 00:00:00-05:00   1.991058   2.521320          0         0   0.210652            1           9
2025-11-25 00:00:00-05:00   1.543076   3.468246          0         0   0.070408            1           9
2025-11-26 00:00:00-05:00  -1.523163   2.533322          0         0   0.199984            0           9
2025-11-28 00:00:00-05:00  -4.549591   4.519776          0         0   0.184774            0           9
2025-12-01 00:00:00-05:00  -6.490860   1.421854          0         0   0.419084            0           0
2025-12-02 00:00:00-05:00  -6.441101   1.179519          0         0   0.438058            0           0
2025-12-03 00:00:00-05:00  -7.396805   0.903579          0         0   0.379427            0           0
2025-12-04 00:00:00-05:00  -0.667007  -0.895783          1         1   0.609475            0           1
2025-12-05 00:00:00-05:00   1.413651  -2.656208          1         1   0.677845            1           9
2025-12-08 00:00:00-05:00   1.732224  -3.824487          1         1   0.694067            1           9

In [ ]:
p=[]
n=[]
for i in df['ROC']:
  if i > 0:
    p.append(i)
  else:
    n.append(i)
pdf = pd.DataFrame({'':p})
ndf = pd.DataFrame({'':n})
print(pdf.mean(), ndf.mean())

    3.137782
dtype: float64    -2.48315
dtype: float64

In [ ]:
print(confusion_matrix(df['Price_label'], df['Price_pred']), '\n', classification_report(df['Price_label'], df['Price_pred']))

[[28 20 52]
 [16 28 51]
 [ 0  0  0]]
               precision    recall  f1-score   support

           0       0.64      0.28      0.39       100
           1       0.58      0.29      0.39        95
           9       0.00      0.00      0.00         0

    accuracy                           0.29       195
   macro avg       0.41      0.19      0.26       195
weighted avg       0.61      0.29      0.39       195

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

In [ ]:
print(df.to_string())

                             Change         RSI  Label  y_pred  final_pred
Date
2025-03-11 00:00:00-04:00 -1.107498   72.487237      0       0           9
2025-03-12 00:00:00-04:00 -0.143494   47.569488      0       1           9
2025-03-13 00:00:00-04:00  0.583092   35.106037      1       1           9
2025-03-14 00:00:00-04:00 -0.476212    3.702579      0       1           9
2025-03-17 00:00:00-04:00 -1.137047   35.732359      0       1           9
2025-03-18 00:00:00-04:00 -0.553940   31.966109      0       1           9
2025-03-19 00:00:00-04:00  0.719147   46.594185      1       1           9
2025-03-20 00:00:00-04:00  1.000984   63.157786      1       0           9
2025-03-21 00:00:00-04:00  1.652122   42.507382      1       0           0
2025-03-24 00:00:00-04:00  2.594788   27.412985      1       1           9
2025-03-25 00:00:00-04:00  2.973801   35.678386      1       1           9
2025-03-26 00:00:00-04:00  1.273102   61.935392      1       0           9
2025-03-27 00:00:00-04:00  2.371269   65.191736      1       0           9
2025-03-28 00:00:00-04:00 -0.427620   81.250379      0       0           9
2025-03-31 00:00:00-04:00 -3.158432   86.179121      0       0           9
2025-04-01 00:00:00-04:00 -3.352806   90.263408      0       0           9
2025-04-02 00:00:00-04:00 -1.341125   70.926721      0       0           9
2025-04-03 00:00:00-04:00 -2.351830   78.638680      0       0           9
2025-04-04 00:00:00-04:00  1.457748   46.918661      1       0           0
2025-04-07 00:00:00-04:00  3.965042   28.187963      1       1           9
2025-04-08 00:00:00-04:00  3.343086   26.206850      1       1           9
2025-04-09 00:00:00-04:00  1.681259   41.626175      1       1           9
2025-04-10 00:00:00-04:00  2.176895   33.194349      1       0           0
2025-04-11 00:00:00-04:00  1.302246   66.233976      1       0           9
2025-04-14 00:00:00-04:00  1.409157  100.000000      1       0           9
2025-04-15 00:00:00-04:00  1.399437   87.229541      1       0           9
2025-04-16 00:00:00-04:00  0.816338   76.452596      1       0           9
2025-04-17 00:00:00-04:00 -1.059288   79.629653      0       0           9
2025-04-21 00:00:00-04:00 -0.952385   70.059796      0       0           9
2025-04-22 00:00:00-04:00 -1.506340   71.014493      0       0           9
2025-04-23 00:00:00-04:00 -0.728882   70.809216      0       0           9
2025-04-24 00:00:00-04:00 -1.195351   60.344804      0       0           9
2025-04-25 00:00:00-04:00 -0.252670   33.731484      0       1           9
2025-04-28 00:00:00-04:00 -0.087463   34.876705      0       1           9
2025-04-29 00:00:00-04:00 -0.612251   20.973646      0       1           9
2025-04-30 00:00:00-04:00 -0.145775   33.479969      0       1           9
2025-05-01 00:00:00-04:00 -0.116623   27.636293      0       1           9
2025-05-02 00:00:00-04:00 -1.098183   44.800126      0       1           9
2025-05-05 00:00:00-04:00 -2.108864   48.148172      0       1           9
2025-05-06 00:00:00-04:00 -2.682243   33.333333      0       0           0
2025-05-07 00:00:00-04:00 -3.148712   46.835426      0       0           0
2025-05-08 00:00:00-04:00  0.427612   47.435820      1       0           0
2025-05-09 00:00:00-04:00  1.438309   28.516718      1       1           9
2025-05-12 00:00:00-04:00  2.332390   19.607778      1       1           9
2025-05-13 00:00:00-04:00  2.653099   16.504860      1       1           9
2025-05-14 00:00:00-04:00  2.614212    5.494735      1       1           9
2025-05-15 00:00:00-04:00 -0.456772   54.526834      0       1           1
2025-05-16 00:00:00-04:00 -0.223511   66.087032      0       0           9
2025-05-19 00:00:00-04:00 -0.145782   82.608826      0       0           9
2025-05-20 00:00:00-04:00 -0.524796   90.746604      0       0           9
2025-05-21 00:00:00-04:00 -0.349861   90.634739      0       0           9
2025-05-22 00:00:00-04:00  0.932961   35.031303      1       1           9
2025-05-23 00:00:00-04:00  0.223511   43.646718      1       1           9
2025-05-27 00:00:00-04:00 -0.602531   45.714081      0       1           9
2025-05-28 00:00:00-04:00  0.213806   37.383068      1       0           0
2025-05-29 00:00:00-04:00 -0.563660   42.241382      0       1           9
2025-05-30 00:00:00-04:00 -0.728867   71.621703      0       0           9
2025-06-02 00:00:00-04:00 -0.223511   56.804478      0       0           9
2025-06-03 00:00:00-04:00  1.156471   37.698407      1       1           9
2025-06-04 00:00:00-04:00  0.680275   55.238209      1       0           9
2025-06-05 00:00:00-04:00  1.292526   36.936934      1       1           9
2025-06-06 00:00:00-04:00  0.170013   31.707438      1       1           9
2025-06-09 00:00:00-04:00 -0.727524   45.147902      0       1           9
2025-06-10 00:00:00-04:00 -2.172028   78.198913      0       0           9
2025-06-11 00:00:00-04:00 -2.301201   66.054947      0       0           9
2025-06-12 00:00:00-04:00 -2.828552   85.185216      0       0           9
2025-06-13 00:00:00-04:00 -1.252777   54.040148      0       0           9
2025-06-16 00:00:00-04:00 -0.303406   33.353699      0       1           9
2025-06-17 00:00:00-04:00  0.009781    6.601829      1       1           9
2025-06-18 00:00:00-04:00  0.254471    6.277777      1       1           9
2025-06-20 00:00:00-04:00  1.458321    0.000000      1       1           9
2025-06-23 00:00:00-04:00  0.988518   29.220891      1       1           9
2025-06-24 00:00:00-04:00  1.428963   44.918087      1       1           9
2025-06-25 00:00:00-04:00  1.252785   50.183028      1       0           9
2025-06-26 00:00:00-04:00  1.840019   55.241900      1       0           9
2025-06-27 00:00:00-04:00  0.665550   75.084316      1       0           9
2025-06-30 00:00:00-04:00 -0.499153   70.281160      0       0           9
2025-07-01 00:00:00-04:00 -2.143433   74.830111      0       0           9
2025-07-02 00:00:00-04:00 -1.115768   70.512856      0       0           9
2025-07-03 00:00:00-04:00 -1.448524   77.646967      0       0           9
2025-07-07 00:00:00-04:00 -1.507256   61.805712      0       0           9
2025-07-08 00:00:00-04:00 -0.861282   42.105352      0       1           9
2025-07-09 00:00:00-04:00 -0.205544   14.332181      0       1           9
2025-07-10 00:00:00-04:00  0.802574   28.076561      1       1           9
2025-07-11 00:00:00-04:00 -0.019585   17.256651      0       1           9
2025-07-14 00:00:00-04:00  0.587234   16.810306      1       1           9
2025-07-15 00:00:00-04:00  0.293625   23.494027      1       1           9
2025-07-16 00:00:00-04:00 -0.107651   39.393558      0       1           9
2025-07-17 00:00:00-04:00 -1.458328   70.297022      0       0           9
2025-07-18 00:00:00-04:00 -0.665535   49.623873      0       0           0
2025-07-21 00:00:00-04:00 -1.937897   62.096495      0       0           9
2025-07-22 00:00:00-04:00 -0.274055   55.395728      0       0           9
2025-07-23 00:00:00-04:00 -0.401283   48.276031      0       1           9
2025-07-24 00:00:00-04:00 -1.184273   11.398995      0       1           9
2025-07-25 00:00:00-04:00 -0.303406   23.016438      0       1           9
2025-07-28 00:00:00-04:00  0.851494    3.302251      1       1           9
2025-07-29 00:00:00-04:00 -0.322975   45.333202      0       1           9
2025-07-30 00:00:00-04:00  0.743828   43.450476      1       1           9
2025-07-31 00:00:00-04:00  2.486008   34.605612      1       1           9
2025-08-01 00:00:00-04:00  1.448517   46.790926      1       1           9
2025-08-04 00:00:00-04:00  1.751938   61.298611      1       0           9
2025-08-05 00:00:00-04:00  1.624702   43.773771      1       1           9
2025-08-06 00:00:00-04:00  0.929802   65.322223      1       0           9
2025-08-07 00:00:00-04:00 -0.861290  100.000000      0       0           9
2025-08-08 00:00:00-04:00 -0.411064   94.577284      0       0           9
2025-08-11 00:00:00-04:00 -1.585548   95.430624      0       0           9
2025-08-12 00:00:00-04:00 -0.567673   93.228830      0       0           9
2025-08-13 00:00:00-04:00  0.234901   77.777373      1       0           9
2025-08-14 00:00:00-04:00  1.086395   24.117661      1       1           9
2025-08-15 00:00:00-04:00  0.205536   39.393939      1       1           9
2025-08-18 00:00:00-04:00 -0.195740   15.677674      0       1           9
2025-08-19 00:00:00-04:00 -1.370224   41.264933      0       1           9
2025-08-20 00:00:00-04:00 -1.830238   53.296784      0       0           9
2025-08-21 00:00:00-04:00 -2.251091   70.036134      0       0           9
2025-08-22 00:00:00-04:00 -1.115761   53.583629      0       0           9
2025-08-25 00:00:00-04:00  0.127228   47.006105      1       1           9
2025-08-26 00:00:00-04:00  0.254463   22.441107      1       1           9
2025-08-27 00:00:00-04:00 -0.567665    4.830747      0       1           9
2025-08-28 00:00:00-04:00 -0.391502    3.999863      0       1           9
2025-08-29 00:00:00-04:00 -1.526833   28.076645      0       1           9
2025-09-02 00:00:00-04:00 -1.174484   54.421559      0       0           9
2025-09-03 00:00:00-04:00 -1.145119   59.701336      0       0           9
2025-09-04 00:00:00-04:00 -0.616608   35.353404      0       1           9
2025-09-05 00:00:00-04:00 -0.929810   38.888576      0       1           9
2025-09-08 00:00:00-04:00 -0.697075    4.117661      0       1           9
2025-09-09 00:00:00-04:00 -1.088348   20.873886      0       1           9
2025-09-10 00:00:00-04:00 -0.260208   21.182402      0       1           9
2025-09-11 00:00:00-04:00 -0.636482   28.859092      0       1           9
2025-09-12 00:00:00-04:00 -0.069031   23.756880      0       1           9
2025-09-15 00:00:00-04:00  0.000000   27.349982      0       1           9
2025-09-16 00:00:00-04:00  0.463539    2.578320      1       1           9
2025-09-17 00:00:00-04:00 -0.581886   43.142924      0       1           9
2025-09-18 00:00:00-04:00 -0.473389   36.003033      0       1           9
2025-09-19 00:00:00-04:00 -0.749550   47.977052      0       1           9
2025-09-22 00:00:00-04:00 -0.167664   50.000000      0       1           1
2025-09-23 00:00:00-04:00 -0.384644   61.032966      0       0           9
2025-09-24 00:00:00-04:00  0.325470   31.446587      1       1           9
2025-09-25 00:00:00-04:00  0.118340   33.784066      1       1           9
2025-09-26 00:00:00-04:00  0.966522   28.409116      1       1           9
2025-09-29 00:00:00-04:00  0.059174   45.549723      1       1           9
2025-09-30 00:00:00-04:00  0.463539   38.461362      1       1           9
2025-10-01 00:00:00-04:00 -0.650925   58.730354      0       1           1
2025-10-02 00:00:00-04:00  0.266289   52.856864      1       0           9
2025-10-03 00:00:00-04:00  0.384636   70.940058      1       0           9
2025-10-06 00:00:00-04:00  0.690376   51.190447      1       0           9
2025-10-07 00:00:00-04:00  0.710098   58.020493      1       0           9
2025-10-08 00:00:00-04:00  0.946793   39.490424      1       1           9
2025-10-09 00:00:00-04:00  1.203217   54.981602      1       0           9
2025-10-10 00:00:00-04:00  1.380745   56.890477      1       0           9
2025-10-13 00:00:00-04:00  1.617439   63.889034      1       0           9
2025-10-14 00:00:00-04:00  3.658958   64.173331      1       0           9
2025-10-15 00:00:00-04:00  3.678680   70.869574      1       0           9
2025-10-16 00:00:00-04:00  2.317680   73.828144      1       0           9
2025-10-17 00:00:00-04:00  1.252525   75.547506      1       0           9
2025-10-20 00:00:00-04:00  1.597710   82.799924      1       0           9
2025-10-21 00:00:00-04:00 -1.045410   90.590749      0       0           9
2025-10-22 00:00:00-04:00 -2.426155   90.988891      0       0           9
2025-10-23 00:00:00-04:00 -0.946800   73.930888      0       0           9
2025-10-24 00:00:00-04:00 -0.798859   64.801835      0       1           1
2025-10-27 00:00:00-04:00 -2.061241   67.456865      0       1           1
2025-10-28 00:00:00-04:00 -1.479362   22.959490      0       1           9
2025-10-29 00:00:00-04:00  0.157806   13.393040      1       1           9
2025-10-30 00:00:00-04:00  0.078896   34.615432      1       1           9
2025-10-31 00:00:00-04:00  1.627312   36.363731      1       1           9
2025-11-03 00:00:00-05:00  2.514908   20.563644      1       1           9
2025-11-04 00:00:00-05:00  2.909409   31.884150      1       1           9
2025-11-05 00:00:00-05:00  2.958725   53.225947      1       1           1
2025-11-06 00:00:00-05:00  1.982353   51.666586      1       0           9
2025-11-07 00:00:00-05:00  0.601601   71.653655      1       0           9
2025-11-10 00:00:00-05:00  0.157806   93.813800      1       0           9
2025-11-11 00:00:00-05:00 -0.384636   94.561376      0       0           9
2025-11-12 00:00:00-05:00 -0.394493   96.011817      0       0           9
2025-11-13 00:00:00-05:00  0.138077   81.904514      1       0           9
2025-11-14 00:00:00-05:00  1.765373   67.428157      1       0           9
2025-11-17 00:00:00-05:00  1.883720   53.636530      1       1           1
2025-11-18 00:00:00-05:00  1.370888   38.181750      1       1           9
2025-11-19 00:00:00-05:00  1.745651   37.951861      1       1           9
2025-11-20 00:00:00-05:00  1.883720   55.303163      1       0           9
2025-11-21 00:00:00-05:00 -0.487831   80.134765      0       0           9
2025-11-24 00:00:00-05:00 -1.404037   83.508815      0       0           9
2025-11-25 00:00:00-05:00 -1.284737   79.828484      0       0           9
2025-11-26 00:00:00-05:00 -1.908554   85.542128      0       0           9
2025-11-28 00:00:00-05:00 -2.592178   86.311721      0       0           9
2025-12-01 00:00:00-05:00 -1.688385   34.091667      0       1           9
2025-12-02 00:00:00-05:00 -0.576042   21.339891      0       1           9
2025-12-03 00:00:00-05:00 -0.595901   24.993095      0       1           9
2025-12-04 00:00:00-05:00 -1.330849   14.125179      0       1           9
2025-12-05 00:00:00-05:00  0.516449    4.844103      1       1           9
2025-12-08 00:00:00-05:00  0.715080   15.725844      1       1           9
2025-12-09 00:00:00-05:00  0.278091   28.676408      1       1           9
2025-12-10 00:00:00-05:00  0.456863   27.612103      1       1           9
2025-12-11 00:00:00-05:00  1.241463   17.788595      1       1           9
2025-12-12 00:00:00-05:00 -0.456856   58.552628      0       0           9
2025-12-15 00:00:00-05:00 -0.754814   61.111072      0       0           9
2025-12-16 00:00:00-05:00 -0.496582   53.804405      0       0           9

In [ ]:
df = pd.DataFrame({'RSI': list(X_test['RSI']), 'Pred':y_pred, 'Label': y_test.values.ravel()})
df['Correct'] = np.where(df['Pred']==df['Label'], True, False)
#df = df.drop(columns = ['Pred', 'Label'])
print(df.to_string())

rsi = list(df['RSI'])
correct = list(df['Correct'])

right = []
wrong = []

for i, x in enumerate(correct):
  if x:
    right.append(rsi[i])
  else:
    wrong.append(rsi[i])

right = pd.DataFrame({'Right':right})
wrong = pd.DataFrame({"Wrong":wrong})

print(f'''
[============== Right ==============]
  Median RSI: {float(right.median())}
  Mean RSI: {float(right.mean())}
  sd: {float(right.std())}

[============== Wrong ==============]
  Median RSI: {float(wrong.median())}
  Mean RSI: {float(wrong.mean())}
  sd: {float(wrong.std())}
''')

           RSI  Pred  Label  Correct
0    20.594489     1      1     True
1    39.326985     0      1    False
2    34.963778     0      1    False
3    44.605535     1      1     True
4    36.015236     1      1     True
5    28.688013     1      1     True
6    41.125659     1      1     True
7    41.608315     1      1     True
8    55.729034     0      0     True
9    74.270434     0      0     True
10   78.046042     0      0     True
11   59.919513     0      1    False
12   60.679134     0      0     True
13   50.060899     1      0    False
14   45.500186     1      0    False
15   56.092725     1      0    False
16   68.034137     0      0     True
17   49.732061     0      0     True
18   30.986188     1      1     True
19   28.070309     1      1     True
20   23.027851     1      1     True
21   61.300028     0      0     True
22   49.258245     0      0     True
23   49.203330     0      0     True
24   49.234780     0      0     True
25   50.906176     0      1    False
26   39.349344     0      1    False
27   39.189956     0      1    False
28   28.191521     0      1    False
29   43.225936     0      1    False
30   56.963317     0      1    False
31   64.365268     0      0     True
32   78.052582     0      0     True
33   78.431150     0      0     True
34   81.122718     0      0     True
35   64.880516     0      0     True
36   62.290142     1      1     True
37   68.668611     0      1    False
38   56.301952     0      1    False
39   48.576429     0      1    False
40   50.093163     0      1    False
41   63.423505     0      1    False
42   75.964747     0      1    False
43   85.358809     0      0     True
44   89.398022     0      0     True
45   91.839193     0      0     True
46   83.279884     0      0     True
47   85.729212     0      0     True
48   71.335084     1      1     True
49   72.596182     0      0     True
50   56.169551     1      1     True
51   63.394553     0      0     True
52   60.114596     0      0     True
53   78.962419     0      0     True
54   68.648467     0      0     True
55   69.903606     0      0     True
56   50.235681     0      0     True
57   45.226073     1      0    False
58   47.945474     0      1    False
59   32.395928     1      1     True
60   12.601360     1      1     True
61   25.198123     1      1     True
62   39.280876     1      1     True
63   53.528935     0      0     True
64   53.792110     0      0     True
65   46.677992     0      1    False
66   53.227175     0      1    False
67   57.269237     0      1    False
68   42.066485     0      1    False
69   49.535142     0      0     True
70   49.691617     0      0     True
71   73.991355     0      0     True
72   62.339300     0      0     True
73   47.595285     0      0     True
74   45.742638     0      0     True
75   43.190004     0      0     True
76   36.181826     1      0    False
77   22.959847     1      1     True
78   45.074157     0      1    False
79   44.751731     0      1    False
80   27.318413     0      1    False
81   33.198206     0      1    False
82   31.604383     0      1    False
83   52.337818     0      1    False
84   56.615185     0      1    False
85   60.719015     0      1    False
86   50.037949     0      1    False
87   64.088907     0      1    False
88   59.731193     0      0     True
89   70.927178     0      0     True
90   68.240559     0      0     True
91   72.329156     0      0     True
92   72.871842     0      0     True
93   29.324242     1      1     True
94   45.417803     0      0     True
95   56.407459     0      0     True
96   50.547279     0      0     True
97   47.511470     0      1    False
98   34.570771     0      1    False
99   29.339744     0      1    False
100  42.192786     0      1    False
101  41.425607     0      1    False
102  60.179883     0      1    False
103  63.279383     0      1    False
104  71.845655     0      0     True
105  79.458801     0      0     True
106  80.716534     0      0     True
107  76.023099     0      0     True
108  63.929044     0      0     True
109  50.629007     1      1     True
110  60.129957     1      1     True
111  46.044254     0      1    False
112  36.232668     1      1     True
113  30.534810     1      1     True
114  65.816576     0      0     True
115  71.754944     0      0     True
116  75.798211     0      0     True
117  70.637621     0      0     True
118  61.486646     0      1    False
119  39.881749     0      1    False
120  34.275216     1      1     True
121  44.503056     0      1    False
122  53.071843     0      1    False
123  69.429905     0      1    False
124  60.000421     0      1    False
125  60.853601     0      1    False
126  62.299633     0      1    False
127  82.734891     0      0     True
128  90.789507     0      0     True
129  92.931743     0      0     True
130  94.294141     0      0     True
131  94.756697     0      0     True
132  77.967650     0      0     True
133  82.038430     0      0     True
134  85.080526     0      0     True
135  69.885322     0      0     True
136  79.265155     0      0     True
137  54.821508     0      0     True
138  66.233902     0      0     True
139  67.907902     0      0     True
140  68.942161     0      0     True
141  77.708209     0      0     True
142  49.764135     0      0     True
143  44.502990     1      0    False
144  63.041909     0      0     True
145  46.373386     0      1    False
146  50.882697     0      1    False
147  48.042264     0      0     True
148  32.276621     1      1     True
149  52.203112     0      1    False
150  47.059352     0      1    False
151  52.275490     0      0     True
152  46.123897     0      1    False
153  56.646203     0      0     True
154  63.498384     0      0     True
155  56.820940     0      1    False
156  51.712220     0      1    False
157  63.136675     0      0     True
158  43.517134     0      1    False
159  61.732398     0      1    False
160  67.438957     0      0     True
161  68.140231     0      0     True
162  42.577209     0      1    False
163  57.793552     0      0     True
164  65.898190     0      0     True
165  44.226441     0      1    False
166  57.217936     0      0     True
167  45.260507     0      0     True
168  35.780651     0      0     True
169  48.663598     0      0     True
170  44.664102     0      0     True
171  38.332419     0      0     True
172  24.539658     0      1    False
173  27.239196     0      0     True
174  33.037662     0      1    False
175  28.305349     0      1    False
176  32.615449     0      1    False
177  26.297465     1      1     True
178  23.597099     1      1     True
179  58.192557     1      1     True
180  59.581129     0      1    False
181  65.862653     0      1    False
182  68.884936     0      1    False
183  68.821294     0      0     True
184  66.516613     0      0     True
185  81.540869     0      0     True
186  85.228844     0      0     True
187  85.448108     0      0     True
188  53.114154     0      1    False
189  59.977012     0      1    False
190  66.801075     0      0     True
191  57.848631     1      1     True
192  70.797462     0      0     True
193  80.789879     0      0     True
194  86.091265     0      0     True
195  56.065334     0      1    False
196  66.474671     0      0     True
197  63.924585     0      0     True
198  69.071085     0      0     True
199  64.247881     0      0     True

[============== Right ==============]
  Median: 63.394553017125
  Mean: 60.188157278065944
  sd: 18.717731022446607

[============== Wrong ==============]
  Median: 48.57642914517433
  Mean: 49.13485796364012
  sd: 11.461630805145886

/tmp/ipykernel_2928/2585415485.py:23: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  Median: {float(right.median())}
/tmp/ipykernel_2928/2585415485.py:24: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  Mean: {float(right.mean())}
/tmp/ipykernel_2928/2585415485.py:25: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  sd: {float(right.std())}
/tmp/ipykernel_2928/2585415485.py:28: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  Median: {float(wrong.median())}
/tmp/ipykernel_2928/2585415485.py:29: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  Mean: {float(wrong.mean())}
/tmp/ipykernel_2928/2585415485.py:30: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  sd: {float(wrong.std())}

In [ ]:
drpcol = list(X_train.columns)

print(len(drpcol))

importances = list(RF.feature_importances_)
sorted_importances = sorted(importances, reverse=True)

for i in range(100):
  drpcol.remove(f'{X.columns[importances.index(sorted_importances[i])]}')

print(len(drpcol))

122
22

In [ ]:
drpcol=[]

In [ ]:
col_names = list(X_train.columns)
importances = list(RF.feature_importances_)
sorted_importances = sorted(importances, reverse=True)
for i,x in enumerate(sorted_importances):
  index = importances.index(x)
  print(col_names[index], x)

NotFittedError: This RandomForestClassifier instance is not fitted yet. Call 'fit' with appropriate arguments before using this estimator.

In [ ]:
stocks = ["AAPL", "TSLA", "JNJ", "JPM", "XOM", "NVDA", "WMT"]

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

date = "2026-01-01"
pred = 'TRIX'.upper()
traceback = -1
classification_type = 'binary'

for stock in stocks:
  X,y = TRIX_data(stock, change_months(date, -100), date, shuffle = False, clean=False, traceback = traceback, classification_type= classification_type, )

  #print(X.shape, y.shape)

  X_test = X.loc['2022-09-01':'2025-11-01']
  y_test = y.loc['2022-09-01':'2025-11-01']

  X = X.iloc[:-850]
  y = y.iloc[:-850]

  X = pd.concat([X,y], axis=1)
  X_train = X.sample(frac=1, random_state=1)

  y_train = X_train.pop("label")

  #print(X_train.shape, y_train.shape, X_test.shape, y_test.shape)

  vote.fit(X_train, y_train.values.ravel())
  y_pred = vote.predict(X_test)
  y_pred_proba = vote.predict_proba(X_test)

  print("[-------------------------------- Accuracy: ",vote.score(X_test, y_test))
  cm = confusion_matrix(y_test, y_pred)
  cf = classification_report(y_test, y_pred)
  #print(cm,'\n',cf)

  ''' #THIS IS USED TO TURN PREDICT PROBAS INTO DATAFRAMES
  df = pd.DataFrame()
  d = {}

  for i in range(len(y_pred_proba[0])):
    d[f'L{i}'] = []

  for i in range(len(y_pred_proba)):
    for j in range(len(y_pred_proba[0])):
      d[f'L{j}'].append(y_pred_proba[i][j])

  for i in d:
      df[f'{i}'] = d[i]

  '''

  df = pd.DataFrame({"":y_pred})

  print(X_train.shape, y_train.shape, X_test.shape, y_test.shape)
  print(f'{stock.upper()}_{pred.upper()}_{classification_type.upper()}({traceback}d).xlsx')
  df.to_excel(f'{stock.upper()}_{pred.upper()}_{classification_type.upper()}({traceback}d).xlsx', index=False)
  df.to_excel(f'/content/drive/MyDrive/SP/New TAx Intermediate Inputs/predicted class as features/{pred.upper()}/FEATURE=CLASS_{stock.upper()}_{pred.upper()}_{classification_type.upper()}({traceback}d).xlsx', index=False)

  #X_test[f'{pred.upper()}'][-800:].to_excel(f'{stock.upper()}_{pred.upper()}_IndicatorValue(today).xlsx', index=False)
  #print(f'{stock.upper()}_{pred.upper()}_IndicatorValue(today).xlsx')
  #X_test[f'{pred.upper()}'][-800:].to_excel(f'/content/drive/MyDrive/SP/New TAx Intermediate Inputs/{pred.upper()}/{stock.upper()}_{pred.upper()}_IndicatorValue(today).xlsx', index=False)

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
[-------------------------------- Accuracy:  0.8264150943396227
(1184, 201) (1184,) (795, 201) (795, 1)
AAPL_TRIX_BINARY(-1d).xlsx
[-------------------------------- Accuracy:  0.8226415094339623
(1184, 201) (1184,) (795, 201) (795, 1)
TSLA_TRIX_BINARY(-1d).xlsx
[-------------------------------- Accuracy:  0.7710691823899372
(1184, 201) (1184,) (795, 201) (795, 1)
JNJ_TRIX_BINARY(-1d).xlsx
[-------------------------------- Accuracy:  0.7987421383647799
(1184, 201) (1184,) (795, 201) (795, 1)
JPM_TRIX_BINARY(-1d).xlsx
[-------------------------------- Accuracy:  0.8062893081761007
(1184, 201) (1184,) (795, 201) (795, 1)
XOM_TRIX_BINARY(-1d).xlsx
[-------------------------------- Accuracy:  0.7823899371069183
(1184, 201) (1184,) (795, 201) (795, 1)
NVDA_TRIX_BINARY(-1d).xlsx
[-------------------------------- Accuracy:  0.7987421383647799
(1184, 201) (1184,) (795, 201) (795, 1)
WMT_TRIX_BINARY(-1d).xlsx

In [ ]:
for stock in stocks:
  X_test[f'{pred.upper()}'][-800:].to_excel(f'{stock.upper()}_{pred.upper()}_IndicatorValue(today).xlsx', index=False)
  print(f'{stock.upper()}_{pred.upper()}_IndicatorValue(today).xlsx')

AAPL_RSI_IndicatorValue(today).xlsx
TSLA_RSI_IndicatorValue(today).xlsx
JNJ_RSI_IndicatorValue(today).xlsx
JPM_RSI_IndicatorValue(today).xlsx
XOM_RSI_IndicatorValue(today).xlsx
NVDA_RSI_IndicatorValue(today).xlsx
WMT_RSI_IndicatorValue(today).xlsx

In [ ]:
y_test

                           label
Date
2022-09-01 00:00:00-04:00      1
2022-09-02 00:00:00-04:00      1
2022-09-06 00:00:00-04:00      1
2022-09-07 00:00:00-04:00      1
2022-09-08 00:00:00-04:00      0
...                          ...
2025-10-27 00:00:00-04:00      0
2025-10-28 00:00:00-04:00      0
2025-10-29 00:00:00-04:00      1
2025-10-30 00:00:00-04:00      1
2025-10-31 00:00:00-04:00      1

[795 rows x 1 columns]

In [ ]:
y_train.loc['2022-08']

Date
2022-08-03 00:00:00-04:00    0
2022-08-02 00:00:00-04:00    0
2022-08-10 00:00:00-04:00    1
2022-08-01 00:00:00-04:00    1
2022-08-05 00:00:00-04:00    0
2022-08-09 00:00:00-04:00    1
2022-08-08 00:00:00-04:00    1
2022-08-04 00:00:00-04:00    0
Name: label, dtype: int64

#AutoML

In [ ]:
!pip install tpot[sklearnex]

Collecting tpot[sklearnex]
  Downloading TPOT-1.1.0-py3-none-any.whl.metadata (1.9 kB)
Requirement already satisfied: numpy>=1.26.4 in /usr/local/lib/python3.12/dist-packages (from tpot[sklearnex]) (2.0.2)
Requirement already satisfied: scipy>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from tpot[sklearnex]) (1.16.3)
Requirement already satisfied: scikit-learn>=1.6 in /usr/local/lib/python3.12/dist-packages (from tpot[sklearnex]) (1.6.1)
Requirement already satisfied: update-checker>=0.16 in /usr/local/lib/python3.12/dist-packages (from tpot[sklearnex]) (0.18.0)
Requirement already satisfied: tqdm>=4.36.1 in /usr/local/lib/python3.12/dist-packages (from tpot[sklearnex]) (4.67.3)
Requirement already satisfied: stopit>=1.1.1 in /usr/local/lib/python3.12/dist-packages (from tpot[sklearnex]) (1.1.2)
Requirement already satisfied: pandas>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from tpot[sklearnex]) (2.2.2)
Requirement already satisfied: joblib>=1.1.1 in /usr/local/lib/python3.12/dist-packages (from tpot[sklearnex]) (1.5.3)
Requirement already satisfied: xgboost>=3.0.0 in /usr/local/lib/python3.12/dist-packages (from tpot[sklearnex]) (3.2.0)
Requirement already satisfied: matplotlib>=3.6.2 in /usr/local/lib/python3.12/dist-packages (from tpot[sklearnex]) (3.10.0)
Requirement already satisfied: traitlets>=5.8.0 in /usr/local/lib/python3.12/dist-packages (from tpot[sklearnex]) (5.14.3)
Requirement already satisfied: lightgbm>=3.3.3 in /usr/local/lib/python3.12/dist-packages (from tpot[sklearnex]) (4.6.0)
Requirement already satisfied: optuna>=3.0.5 in /usr/local/lib/python3.12/dist-packages (from tpot[sklearnex]) (4.7.0)
Requirement already satisfied: networkx>=3.0 in /usr/local/lib/python3.12/dist-packages (from tpot[sklearnex]) (3.6.1)
Requirement already satisfied: dask>=2024.4.2 in /usr/local/lib/python3.12/dist-packages (from tpot[sklearnex]) (2026.1.2)
Requirement already satisfied: distributed>=2024.4.2 in /usr/local/lib/python3.12/dist-packages (from tpot[sklearnex]) (2026.1.2)
Collecting dask-expr>=1.0.12 (from tpot[sklearnex])
  Downloading dask_expr-2.0.0-py3-none-any.whl.metadata (2.3 kB)
Requirement already satisfied: dask-jobqueue>=0.8.5 in /usr/local/lib/python3.12/dist-packages (from tpot[sklearnex]) (0.9.0)
Requirement already satisfied: func-timeout>=4.3.5 in /usr/local/lib/python3.12/dist-packages (from tpot[sklearnex]) (4.3.5)
Collecting configspace>=1.1.1 (from tpot[sklearnex])
  Downloading configspace-1.2.2-py3-none-any.whl.metadata (8.0 kB)
Collecting dill>=0.3.9 (from tpot[sklearnex])
  Downloading dill-0.4.1-py3-none-any.whl.metadata (10 kB)
Requirement already satisfied: seaborn>=0.13.2 in /usr/local/lib/python3.12/dist-packages (from tpot[sklearnex]) (0.13.2)
Requirement already satisfied: scikit-learn-intelex>=2023.2.1 in /usr/local/lib/python3.12/dist-packages (from tpot[sklearnex]) (2025.10.1)
Requirement already satisfied: pyparsing in /usr/local/lib/python3.12/dist-packages (from configspace>=1.1.1->tpot[sklearnex]) (3.3.2)
Requirement already satisfied: typing_extensions in /usr/local/lib/python3.12/dist-packages (from configspace>=1.1.1->tpot[sklearnex]) (4.15.0)
Requirement already satisfied: more_itertools in /usr/local/lib/python3.12/dist-packages (from configspace>=1.1.1->tpot[sklearnex]) (10.8.0)
Requirement already satisfied: click>=8.1 in /usr/local/lib/python3.12/dist-packages (from dask>=2024.4.2->tpot[sklearnex]) (8.3.1)
Requirement already satisfied: cloudpickle>=3.0.0 in /usr/local/lib/python3.12/dist-packages (from dask>=2024.4.2->tpot[sklearnex]) (3.1.2)
Requirement already satisfied: fsspec>=2021.09.0 in /usr/local/lib/python3.12/dist-packages (from dask>=2024.4.2->tpot[sklearnex]) (2025.3.0)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from dask>=2024.4.2->tpot[sklearnex]) (26.0)
Requirement already satisfied: partd>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from dask>=2024.4.2->tpot[sklearnex]) (1.4.2)
Requirement already satisfied: pyyaml>=5.3.1 in /usr/local/lib/python3.12/dist-packages (from dask>=2024.4.2->tpot[sklearnex]) (6.0.3)
Requirement already satisfied: toolz>=0.12.0 in /usr/local/lib/python3.12/dist-packages (from dask>=2024.4.2->tpot[sklearnex]) (0.12.1)
Requirement already satisfied: jinja2>=2.10.3 in /usr/local/lib/python3.12/dist-packages (from distributed>=2024.4.2->tpot[sklearnex]) (3.1.6)
Requirement already satisfied: locket>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from distributed>=2024.4.2->tpot[sklearnex]) (1.0.0)
Requirement already satisfied: msgpack>=1.0.2 in /usr/local/lib/python3.12/dist-packages (from distributed>=2024.4.2->tpot[sklearnex]) (1.1.2)
Requirement already satisfied: psutil>=5.8.0 in /usr/local/lib/python3.12/dist-packages (from distributed>=2024.4.2->tpot[sklearnex]) (5.9.5)
Requirement already satisfied: sortedcontainers>=2.0.5 in /usr/local/lib/python3.12/dist-packages (from distributed>=2024.4.2->tpot[sklearnex]) (2.4.0)
Requirement already satisfied: tblib!=3.2.0,!=3.2.1,>=1.6.0 in /usr/local/lib/python3.12/dist-packages (from distributed>=2024.4.2->tpot[sklearnex]) (3.2.2)
Requirement already satisfied: tornado>=6.2.0 in /usr/local/lib/python3.12/dist-packages (from distributed>=2024.4.2->tpot[sklearnex]) (6.5.1)
Requirement already satisfied: urllib3>=1.26.5 in /usr/local/lib/python3.12/dist-packages (from distributed>=2024.4.2->tpot[sklearnex]) (2.5.0)
Requirement already satisfied: zict>=3.0.0 in /usr/local/lib/python3.12/dist-packages (from distributed>=2024.4.2->tpot[sklearnex]) (3.0.0)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.6.2->tpot[sklearnex]) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.6.2->tpot[sklearnex]) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.6.2->tpot[sklearnex]) (4.61.1)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.6.2->tpot[sklearnex]) (1.4.9)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.6.2->tpot[sklearnex]) (11.3.0)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.6.2->tpot[sklearnex]) (2.9.0.post0)
Requirement already satisfied: alembic>=1.5.0 in /usr/local/lib/python3.12/dist-packages (from optuna>=3.0.5->tpot[sklearnex]) (1.18.4)
Requirement already satisfied: colorlog in /usr/local/lib/python3.12/dist-packages (from optuna>=3.0.5->tpot[sklearnex]) (6.10.1)
Requirement already satisfied: sqlalchemy>=1.4.2 in /usr/local/lib/python3.12/dist-packages (from optuna>=3.0.5->tpot[sklearnex]) (2.0.46)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas>=2.2.0->tpot[sklearnex]) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas>=2.2.0->tpot[sklearnex]) (2025.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn>=1.6->tpot[sklearnex]) (3.6.0)
Requirement already satisfied: daal==2025.10.1 in /usr/local/lib/python3.12/dist-packages (from scikit-learn-intelex>=2023.2.1->tpot[sklearnex]) (2025.10.1)
Requirement already satisfied: tbb==2022.* in /usr/local/lib/python3.12/dist-packages (from daal==2025.10.1->scikit-learn-intelex>=2023.2.1->tpot[sklearnex]) (2022.3.1)
Requirement already satisfied: tcmlib==1.* in /usr/local/lib/python3.12/dist-packages (from tbb==2022.*->daal==2025.10.1->scikit-learn-intelex>=2023.2.1->tpot[sklearnex]) (1.4.1)
Requirement already satisfied: requests>=2.3.0 in /usr/local/lib/python3.12/dist-packages (from update-checker>=0.16->tpot[sklearnex]) (2.32.4)
Requirement already satisfied: nvidia-nccl-cu12 in /usr/local/lib/python3.12/dist-packages (from xgboost>=3.0.0->tpot[sklearnex]) (2.29.3)
Requirement already satisfied: Mako in /usr/local/lib/python3.12/dist-packages (from alembic>=1.5.0->optuna>=3.0.5->tpot[sklearnex]) (1.3.10)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2>=2.10.3->distributed>=2024.4.2->tpot[sklearnex]) (3.0.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.7->matplotlib>=3.6.2->tpot[sklearnex]) (1.17.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.3.0->update-checker>=0.16->tpot[sklearnex]) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests>=2.3.0->update-checker>=0.16->tpot[sklearnex]) (3.11)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests>=2.3.0->update-checker>=0.16->tpot[sklearnex]) (2026.1.4)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy>=1.4.2->optuna>=3.0.5->tpot[sklearnex]) (3.3.1)
Downloading configspace-1.2.2-py3-none-any.whl (117 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 117.6/117.6 kB 3.2 MB/s eta 0:00:00
Downloading dask_expr-2.0.0-py3-none-any.whl (3.2 kB)
Downloading dill-0.4.1-py3-none-any.whl (120 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 120.0/120.0 kB 4.1 MB/s eta 0:00:00
Downloading TPOT-1.1.0-py3-none-any.whl (215 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 215.1/215.1 kB 12.6 MB/s eta 0:00:00
Installing collected packages: dill, configspace, dask-expr, tpot
  Attempting uninstall: dill
    Found existing installation: dill 0.3.8
    Uninstalling dill-0.3.8:
      Successfully uninstalled dill-0.3.8
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
datasets 4.0.0 requires dill<0.3.9,>=0.3.0, but you have dill 0.4.1 which is incompatible.
Successfully installed configspace-1.2.2 dask-expr-2.0.0 dill-0.4.1 tpot-1.1.0

In [ ]:
import tpot
from tpot import TPOTClassifier

In [ ]:
stock = "tsla"
date = "2026-01-01"
X,y = momentum_data(stock, change_months(date, -60), date,shuffle = False)

X_test = X.iloc[-200:]
y_test = y.iloc[-200:]

X = X.iloc[:-222]
y = y.iloc[:-222]

X = pd.concat([X,y], axis=1)
X_train = X.sample(frac=1, random_state=1)

y_train = X_train.pop("label")

"Train: ", X_train.shape, y_train.shape, "Test:", X_test.shape, y_train.shape

('Train: ', (806, 87), (806,), 'Test:', (200, 87), (806,))

In [ ]:
TPOT = tpot.TPOTClassifier(
    scorers = 'accuracy',
    generations = 50, #how many interations per algorithm is tested
    population_size = 10,
    verbose=4,
    cv = 5,
    max_time_mins = 240,
    preprocessing=False,
    early_stop=5,
    )
TPOT.fit(X_train, y_train)

/usr/local/lib/python3.12/dist-packages/tpot/tpot_estimator/estimator.py:458: UserWarning: Both generations and max_time_mins are set. TPOT will terminate when the first condition is met.
  warnings.warn("Both generations and max_time_mins are set. TPOT will terminate when the first condition is met.")
/usr/local/lib/python3.12/dist-packages/distributed/node.py:188: UserWarning: Port 8787 is already in use.
Perhaps you already have a cluster running?
Hosting the HTTP server on port 39909 instead
  warnings.warn(
INFO:distributed.scheduler:State start
INFO:distributed.scheduler:  Scheduler at:     tcp://127.0.0.1:45331
INFO:distributed.scheduler:  dashboard at:  http://127.0.0.1:39909/status
INFO:distributed.scheduler:Registering Worker plugin shuffle
INFO:distributed.nanny:        Start Nanny at: 'tcp://127.0.0.1:43585'
INFO:distributed.scheduler:Register worker addr: tcp://127.0.0.1:33083 name: 0
INFO:distributed.scheduler:Starting worker compute stream, tcp://127.0.0.1:33083
INFO:distributed.core:Starting established connection to tcp://127.0.0.1:41486
INFO:distributed.scheduler:Receive client connection: Client-2513b375-0fc7-11f1-8e5e-0242ac1c000c
INFO:distributed.core:Starting established connection to tcp://127.0.0.1:41502
/usr/local/lib/python3.12/dist-packages/tpot/tpot_estimator/estimator.py:537: UserWarning: Labels are not encoded as ints from 0 to N. For compatibility with some classifiers such as sklearn, TPOT has encoded y with the sklearn LabelEncoder. When using pipelines outside the main TPOT estimator class, you can encode the labels with est.label_encoder_
  warnings.warn("Labels are not encoded as ints from 0 to N. For compatibility with some classifiers such as sklearn, TPOT has encoded y with the sklearn LabelEncoder. When using pipelines outside the main TPOT estimator class, you can encode the labels with est.label_encoder_")
Generation:   2%|▏         | 1/50 [04:55<4:01:10, 295.31s/it]

Generation:  1
Best accuracy_score score: 0.4131124913733609

Generation:   4%|▍         | 2/50 [14:01<5:54:06, 442.63s/it]

Generation:  2
Best accuracy_score score: 0.44424507323058043

Generation:   6%|▌         | 3/50 [21:29<5:48:44, 445.20s/it]

Generation:  3
Best accuracy_score score: 0.44424507323058043

Generation:   8%|▊         | 4/50 [28:59<5:42:52, 447.22s/it]

Generation:  4
Best accuracy_score score: 0.44424507323058043

Generation:  10%|█         | 5/50 [36:31<5:36:35, 448.79s/it]

Generation:  5
Best accuracy_score score: 0.4515911356491067

Generation:  12%|█▏        | 6/50 [42:30<5:06:49, 418.39s/it]

Generation:  6
Best accuracy_score score: 0.46155202821869484

Generation:  14%|█▍        | 7/50 [45:41<4:06:31, 343.98s/it]

Generation:  7
Best accuracy_score score: 0.46897477187332265

Generation:  16%|█▌        | 8/50 [50:16<3:45:23, 321.98s/it]

Generation:  8
Best accuracy_score score: 0.46897477187332265

Generation:  18%|█▊        | 9/50 [53:52<3:17:22, 288.84s/it]

Generation:  9
Best accuracy_score score: 0.46897477187332265

Generation:  20%|██        | 10/50 [59:56<3:28:09, 312.24s/it]

Generation:  10
Best accuracy_score score: 0.46897477187332265

Generation:  22%|██▏       | 11/50 [1:04:37<3:16:37, 302.50s/it]

Generation:  11
Best accuracy_score score: 0.47526263323364776

Generation:  24%|██▍       | 12/50 [1:06:18<2:32:53, 241.41s/it]

Generation:  12
Best accuracy_score score: 0.4826086956521739

Generation:  26%|██▌       | 13/50 [1:09:57<2:24:36, 234.49s/it]

Generation:  13
Best accuracy_score score: 0.4826086956521739

Generation:  28%|██▊       | 14/50 [1:13:51<2:20:31, 234.19s/it]

Generation:  14
Best accuracy_score score: 0.4875469672571121

Generation:  30%|███       | 15/50 [1:17:42<2:16:09, 233.42s/it]

Generation:  15
Best accuracy_score score: 0.4875469672571121

Generation:  32%|███▏      | 16/50 [1:19:15<1:48:17, 191.11s/it]

Generation:  16
Best accuracy_score score: 0.4875469672571121

Generation:  34%|███▍      | 17/50 [1:25:05<2:11:23, 238.90s/it]

Generation:  17
Best accuracy_score score: 0.49132735219691737

Generation:  36%|███▌      | 18/50 [1:27:59<1:57:03, 219.50s/it]

Generation:  18
Best accuracy_score score: 0.49132735219691737

Generation:  38%|███▊      | 19/50 [1:31:57<1:56:14, 224.99s/it]

Generation:  19
Best accuracy_score score: 0.4962579556782455

Generation:  40%|████      | 20/50 [1:34:59<1:45:58, 211.96s/it]

Generation:  20
Best accuracy_score score: 0.4962579556782455

Generation:  42%|████▏     | 21/50 [1:39:49<1:53:47, 235.44s/it]

Generation:  21
Best accuracy_score score: 0.4962579556782455

Generation:  44%|████▍     | 22/50 [1:44:46<1:58:31, 254.00s/it]

Generation:  22
Best accuracy_score score: 0.4962579556782455

Generation:  46%|████▌     | 23/50 [1:48:52<1:53:12, 251.58s/it]

Generation:  23
Best accuracy_score score: 0.4962579556782455

Generation:  48%|████▊     | 24/50 [1:53:42<1:53:59, 263.05s/it]

Generation:  24
Best accuracy_score score: 0.497538532321141

Generation:  50%|█████     | 25/50 [1:57:27<1:44:52, 251.70s/it]

Generation:  25
Best accuracy_score score: 0.5012575722720649

Generation:  52%|█████▏    | 26/50 [2:02:45<1:48:36, 271.50s/it]

Generation:  26
Best accuracy_score score: 0.5012575722720649

INFO:distributed.core:Event loop was unresponsive in Scheduler for 3.08s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
INFO:distributed.core:Event loop was unresponsive in Scheduler for 3.39s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
INFO:distributed.core:Event loop was unresponsive in Scheduler for 3.44s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
INFO:distributed.core:Event loop was unresponsive in Scheduler for 3.49s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
INFO:distributed.core:Event loop was unresponsive in Scheduler for 3.34s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
INFO:distributed.core:Event loop was unresponsive in Nanny for 3.39s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
INFO:distributed.core:Event loop was unresponsive in Scheduler for 3.41s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
INFO:distributed.core:Event loop was unresponsive in Nanny for 3.48s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
INFO:distributed.core:Event loop was unresponsive in Scheduler for 3.50s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
Generation:  54%|█████▍    | 27/50 [2:06:54<1:41:33, 264.92s/it]

Generation:  27
Best accuracy_score score: 0.5012575722720649

Generation:  56%|█████▌    | 28/50 [2:11:13<1:36:25, 262.98s/it]

Generation:  28
Best accuracy_score score: 0.5012575722720649

INFO:distributed.core:Event loop was unresponsive in Nanny for 3.52s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
INFO:distributed.core:Event loop was unresponsive in Scheduler for 3.52s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
INFO:distributed.core:Event loop was unresponsive in Scheduler for 3.52s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
INFO:distributed.core:Event loop was unresponsive in Scheduler for 3.53s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
INFO:distributed.core:Event loop was unresponsive in Scheduler for 3.53s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
INFO:distributed.core:Event loop was unresponsive in Scheduler for 3.53s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
INFO:distributed.core:Event loop was unresponsive in Scheduler for 3.54s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
INFO:distributed.core:Event loop was unresponsive in Scheduler for 3.53s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
INFO:distributed.core:Event loop was unresponsive in Nanny for 3.59s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
Generation:  58%|█████▊    | 29/50 [2:15:01<1:28:22, 252.48s/it]

Generation:  29
Best accuracy_score score: 0.5012575722720649

Generation:  60%|██████    | 30/50 [2:18:03<1:17:08, 231.45s/it]

Generation:  30
Best accuracy_score score: 0.5012575722720649

INFO:distributed.core:Event loop was unresponsive in Scheduler for 3.25s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
INFO:distributed.core:Event loop was unresponsive in Scheduler for 3.25s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
INFO:distributed.core:Event loop was unresponsive in Scheduler for 3.55s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
INFO:distributed.core:Event loop was unresponsive in Scheduler for 3.55s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
INFO:distributed.core:Event loop was unresponsive in Nanny for 3.63s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
INFO:distributed.core:Event loop was unresponsive in Scheduler for 3.72s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
INFO:distributed.core:Event loop was unresponsive in Nanny for 3.84s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
INFO:distributed.core:Event loop was unresponsive in Scheduler for 3.94s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
INFO:distributed.core:Event loop was unresponsive in Scheduler for 3.81s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
Generation:  60%|██████    | 30/50 [2:22:06<1:34:44, 284.20s/it]

Generation:  31
Best accuracy_score score: 0.5012575722720649
Early stop

INFO:distributed.scheduler:Retire worker addresses (stimulus_id='retire-workers-1771756875.136514') (0,)
INFO:distributed.nanny:Closing Nanny at 'tcp://127.0.0.1:43585'. Reason: nanny-close
INFO:distributed.nanny:Nanny asking worker to close. Reason: nanny-close
INFO:distributed.core:Received 'close-stream' from tcp://127.0.0.1:41486; closing.
INFO:distributed.scheduler:Remove worker addr: tcp://127.0.0.1:33083 name: 0 (stimulus_id='handle-worker-cleanup-1771756875.1535032')
ERROR:distributed.scheduler:Removing worker 'tcp://127.0.0.1:33083' caused the cluster to lose scattered data, which can't be recovered: {'ndarray-defbd73be9d08fd262eb937088bc047d', 'DataFrame-9a2020d7e71bfa867cc122e0fea7a809'} (stimulus_id='handle-worker-cleanup-1771756875.1535032')
INFO:distributed.scheduler:Lost all workers
INFO:distributed.nanny:Nanny at 'tcp://127.0.0.1:43585' closed.
INFO:distributed.scheduler:Closing scheduler. Reason: unknown
INFO:distributed.scheduler:Scheduler closing all comms

TPOTClassifier(cv=5, early_stop=5, max_time_mins=240, scorers='accuracy',
               search_space=<tpot.search_spaces.pipelines.sequential.SequentialPipeline object at 0x78c92cf79e50>,
               verbose=4)

In [ ]:
score = TPOT.fitted_pipeline_.score(X_test, y_test)
print(f"Test Score: {score}")

Test Score: 0.08

In [ ]:
# Print the entire pipeline structure
print(TPOT.fitted_pipeline_)

# To specifically see the hyperparameters of the final model:
best_steps = list(TPOT.fitted_pipeline_.named_steps.keys())
print(f"Model: {best_steps}")
try:
  for i in range(len(best_steps)):
    print(f"Hyperparameters: {TPOT.fitted_pipeline_.named_steps[best_steps[i]].get_params()}")
except:
  print(1)

Pipeline(steps=[('minmaxscaler', MinMaxScaler()),
                ('rfe',
                 RFE(estimator=ExtraTreesClassifier(bootstrap=np.True_,
                                                    criterion=np.str_('entropy'),
                                                    max_features=0.2736539257821,
                                                    min_samples_leaf=4,
                                                    min_samples_split=16,
                                                    n_jobs=1),
                     step=0.8740781381637)),
                ('featureunion-1',
                 FeatureUnion(transformer_list=[('skiptransformer',
                                                 SkipTransformer()),
                                                ('passthrough',
                                                 Passthro...
                               feature_types=None, feature_weights=None,
                               gamma=0.0048414610878, grow_policy=None,
                               importance_type=None,
                               interaction_constraints=None,
                               learning_rate=0.140862028272, max_bin=None,
                               max_cat_threshold=None, max_cat_to_onehot=None,
                               max_delta_step=None, max_depth=14,
                               max_leaves=None, min_child_weight=1, missing=nan,
                               monotone_constraints=None, multi_strategy=None,
                               n_estimators=100, n_jobs=1, nthread=1, ...))])
Model: ['minmaxscaler', 'rfe', 'featureunion-1', 'featureunion-2', 'xgbclassifier']
Hyperparameters: {'clip': False, 'copy': True, 'feature_range': (0, 1)}
Hyperparameters: {'estimator__bootstrap': np.True_, 'estimator__ccp_alpha': 0.0, 'estimator__class_weight': None, 'estimator__criterion': np.str_('entropy'), 'estimator__max_depth': None, 'estimator__max_features': 0.2736539257821, 'estimator__max_leaf_nodes': None, 'estimator__max_samples': None, 'estimator__min_impurity_decrease': 0.0, 'estimator__min_samples_leaf': 4, 'estimator__min_samples_split': 16, 'estimator__min_weight_fraction_leaf': 0.0, 'estimator__monotonic_cst': None, 'estimator__n_estimators': 100, 'estimator__n_jobs': 1, 'estimator__oob_score': False, 'estimator__random_state': None, 'estimator__verbose': 0, 'estimator__warm_start': False, 'estimator': ExtraTreesClassifier(bootstrap=np.True_, criterion=np.str_('entropy'),
                     max_features=0.2736539257821, min_samples_leaf=4,
                     min_samples_split=16, n_jobs=1), 'importance_getter': 'auto', 'n_features_to_select': None, 'step': 0.8740781381637, 'verbose': 0}
Hyperparameters: {'n_jobs': None, 'transformer_list': [('skiptransformer', SkipTransformer()), ('passthrough', Passthrough())], 'transformer_weights': None, 'verbose': False, 'verbose_feature_names_out': True, 'skiptransformer': SkipTransformer(), 'passthrough': Passthrough()}
Hyperparameters: {'n_jobs': None, 'transformer_list': [('skiptransformer', SkipTransformer()), ('passthrough', Passthrough())], 'transformer_weights': None, 'verbose': False, 'verbose_feature_names_out': True, 'skiptransformer': SkipTransformer(), 'passthrough': Passthrough()}
Hyperparameters: {'objective': 'multi:softprob', 'base_score': None, 'booster': None, 'callbacks': None, 'colsample_bylevel': None, 'colsample_bynode': None, 'colsample_bytree': None, 'device': None, 'early_stopping_rounds': None, 'enable_categorical': False, 'eval_metric': None, 'feature_types': None, 'feature_weights': None, 'gamma': 0.0048414610878, 'grow_policy': None, 'importance_type': None, 'interaction_constraints': None, 'learning_rate': 0.140862028272, 'max_bin': None, 'max_cat_threshold': None, 'max_cat_to_onehot': None, 'max_delta_step': None, 'max_depth': 14, 'max_leaves': None, 'min_child_weight': 1, 'missing': nan, 'monotone_constraints': None, 'multi_strategy': None, 'n_estimators': 100, 'n_jobs': 1, 'num_parallel_tree': None, 'random_state': None, 'reg_alpha': 0.2100167269282, 'reg_lambda': 0.2865621553377, 'sampling_method': None, 'scale_pos_weight': None, 'subsample': 0.9859286312385, 'tree_method': None, 'validate_parameters': None, 'verbosity': 0, 'nthread': 1}

In [ ]:
list(TPOT.fitted_pipeline_.named_steps.keys())

In [ ]:
Opted = RandomForestClassifier(
        bootstrap= np.True_,
        ccp_alpha= 0.0,
        class_weight= 'balanced',
        criterion= np.str_('entropy'),
        max_depth= None,
        max_features= 0.1317695107895,
        max_leaf_nodes= None,
        max_samples= None,
        min_impurity_decrease= 0.0,
        min_samples_leaf= 1,
        min_samples_split= 5,
        min_weight_fraction_leaf= 0.0,
        monotonic_cst= None,
        n_estimators= 128,
        n_jobs= 1,
        oob_score= False,
        random_state= None,
        verbose= 0,
        warm_start= False
)

In [ ]:
Opted.fit(X_train, y_train)
Opted.score(X_test, y_test)

0.26

In [ ]:
y_pred = Opted.predict(X_test)
cm = confusion_matrix(y_test, y_pred)
cf = classification_report(y_test, y_pred)
print(cm, "\n",cf)

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(

ValueError: X has 95 features, but RandomForestClassifier is expecting 7896 features as input.